### PR TITLE
[SVG] Read large-arc and sweep as flags

### LINKED ISSUE #4683: Minified arc in SVG results in degenerate glyph
Arch Linux, d867fe0ab9c1edb2a5d268f713b72bef7146d59b

I've been bug hunting with a music note icon from the Adwaita icon set.&dagger; So far it's revealed bugs in Python `svg.path` (regebro/svg.path#69), Dolphin ([KDE bug 434863](https://bugs.kde.org/show_bug.cgi?id=434863
)), and Qt ([QTBUG-92184](https://bugreports.qt.io/browse/QTBUG-92184)).

FontForge cannot understand this SVG either. The best notes for fixing it are found in regebro/svg.path#69:
image

Broken:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path d="M5 1v7.344A3.574 3.574 0 003.5 8 3.515 3.515 0 000 11.5C0 13.421 1.579 15 3.5 15A3.517 3.517 0 007 11.531v-7.53h6v4.343A3.574 3.574 0 0011.5 8 3.515 3.515 0 008 11.5c0 1.921 1.579 3.5 3.5 3.5 1.9 0 3.465-1.546 3.5-3.437V1z" style="line-height:normal;-inkscape-font-specification:Sans;text-indent:0;text-align:start;text-decoration-line:none;text-transform:none;marker:none" color="#000" font-weight="400" font-family="Sans" overflow="visible" fill="#474747"/></svg>
```

Fixed by unminifying arcs:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path d="M5 1v7.344A3.574 3.574 0 0 0 3.5 8 3.515 3.515 0 0 0 0 11.5C0 13.421 1.579 15 3.5 15A3.517 3.517 0 0 0 7 11.531v-7.53h6v4.343A3.574 3.574 0 0 0 11.5 8 3.515 3.515 0 0 0 8 11.5c0 1.921 1.579 3.5 3.5 3.5 1.9 0 3.465-1.546 3.5-3.437V1z" style="line-height:normal;-inkscape-font-specification:Sans;text-indent:0;text-align:start;text-decoration-line:none;text-transform:none;marker:none" color="#000" font-weight="400" font-family="Sans" overflow="visible" fill="#474747"/></svg>
```

Diff:
```bash
git diff --word-diff -- /tmp/audio-*
```
```diff
diff --git a/tmp/audio-fixed.svg b/tmp/audio-x-generic-symbolic.svg
index 8e9e81f..10c2ab6 100644
--- a/tmp/audio-fixed.svg
+++ b/tmp/audio-x-generic-symbolic.svg
@@ -1 +1 @@
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path d="M5 1v7.344A3.574 3.574 0 [-0 0 3.5-]{+003.5+} 8 3.515 3.515 0 [-0 0 0-]{+000+} 11.5C0 13.421 1.579 15 3.5 15A3.517 3.517 0 [-0 0 7-]{+007+} 11.531v-7.53h6v4.343A3.574 3.574 0 [-0 0 11.5-]{+0011.5+} 8 3.515 3.515 0 [-0 0 8-]{+008+} 11.5c0 1.921 1.579 3.5 3.5 3.5 1.9 0 3.465-1.546 3.5-3.437V1z" style="line-height:normal;-inkscape-font-specification:Sans;text-indent:0;text-align:start;text-decoration-line:none;text-transform:none;marker:none" color="#000" font-weight="400" font-family="Sans" overflow="visible" fill="#474747"/></svg>
```

Here's the SFD, but you can get it just as easily by using SVG import with default options.
```sfd
SplineFontDB: 3.2
FontName: Untitled1
FullName: Untitled1
FamilyName: Untitled1
Weight: Regular
Ascent: 800
Descent: 200
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
Encoding: Custom
BeginChars: 1 1

StartChar: musicnote
Encoding: 0 -1 0
Width: 1000
LayerCount: 2
Fore
SplineSet
895.0625 529.091796875 m 1
 895.0625 308.779296875 l 1
 922.953125 328.14453125 941.234375 360.400390625 941.234375 396.904296875 c 0
 941.234375 456.083984375 893.1875 504.130859375 834.0078125 504.130859375 c 0
 774.828125 504.130859375 726.78125 456.083984375 726.78125 396.904296875 c 0
 726.78125 366.318359375 739.49609375 338.6328125 760.0625 319.091796875 c 1
 693.822265625 319.091796875 640.0625 372.8515625 640.0625 439.091796875 c 0
 640.0625 505.33203125 693.822265625 559.091796875 760.0625 559.091796875 c 1
 745.0625 156.46484375 792.435546875 109.091796875 850.0625 109.091796875 c 1
 835.58984375 106.220703125 820.6484375 104.7265625 805.35546875 104.7265625 c 0
 678.763671875 104.7265625 575.990234375 207.5 575.990234375 334.091796875 c 0
 575.990234375 445.390625 655.765625 538.26171875 761 559.091796875 c 2
 761 785 l 1
NamedP: "Broken"
 941 785 l 1
 941 654.6875 l 1
 914.10546875 669.189453125 883.373046875 677.421875 850.736328125 677.421875 c 0
 745.501953125 677.421875 660.1015625 591.9921875 660.1015625 486.787109375 c 0
 660.1015625 414.21875 700.326171875 351.2890625 760.0625 319.091796875 c 1
 693.822265625 319.091796875 640.0625 372.8515625 640.0625 439.091796875 c 0
 640.0625 505.33203125 693.822265625 559.091796875 760.0625 559.091796875 c 1
 760.0625 501.46484375 807.435546875 454.091796875 865.0625 454.091796875 c 0
 922.07421875 454.091796875 969.0078125 500.46875 970.0625 557.1875 c 1
 970.0625 529.091796875 l 1
 895.0625 529.091796875 l 1
161 785 m 1
NamedP: "Fixed (unminified)"
 461 785 l 1
 461 468.095703125 l 2
 459.9453125 411.376953125 413.01171875 365 356 365 c 0
 298.373046875 365 251 412.373046875 251 470 c 0
 251.234375 527.83203125 298.16796875 574.765625 356 575 c 0
 372.0546875 574.853515625 387.376953125 571.1328125 401 564.6875 c 1
 401 694.970703125 l 1
 221 694.970703125 l 1
 221 469.0625 l 2
 220.208984375 411.669921875 173.509765625 365.263671875 116 365 c 0
 58.373046875 365 11 412.373046875 11 470 c 0
 11.234375 527.83203125 58.16796875 574.765625 116 575 c 0
 132.0546875 574.853515625 147.376953125 571.1328125 161 564.6875 c 1
 161 785 l 1
EndSplineSet
EndChar
EndChars
EndSplineFont
```

<sub>&dagger; `/usr/share/icons/Adwaita/scalable/mimetypes/audio-x-generic-symbolic.svg`</sub>

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Otherwise they can be considered part of one large integer.

Closes #4683.

### Type of change

- **Bug fix**

### CODE REVIEW

File: fontforge/svg.c [hunk 1]
```diff
@@ -1553,9 +1553,11 @@ static SplineSet *SVGParsePath(xmlChar *path) {
 		end = skipcomma(end);
 		axisrot = strtod(end,&end)*FF_PI/180;
 		end = skipcomma(end);
-		large_arc = strtol(end,&end,10);
+		large_arc = *end != '0';
+		end++;
```
Comment (skef) [inline fontforge/svg.c:1557]: `skipcomma()` is

```
static char *skipcomma(char *pt) {
    while ( isspace(*pt))++pt;
    if ( *pt==',' ) ++pt;
return( pt );
```
And therefore it reads leading spaces up to a potential comma and then stops. `strtol()` [eats leading whitespace](https://man7.org/linux/man-pages/man3/strtol.3.html). So it seems like this change would break a path fragment like `A 3.517, 3.517, 0, -0, 0, 7` because `*end` would just be a space here.

Comment (ctrlcctrlv) [reply fontforge/svg.c:1557]: I see, so I need to also eat leading whitespace if any before doing `*end`, right?

Comment (skef) [reply fontforge/svg.c:1557]: This is just by inspection on my part, but yes I think that's right.

**Review by skef — APPROVED** [review]
This looks like it should work. Thorough testing would also be a virtue.

**Comment by ctrlcctrlv** [comment]
@jtanx This is ready to merge, but I can't merge with failing statuses. I re-ran them, but WIN32 build is still failing because it can't find gettext. I think something changed over there. AppVeyor failing for another reason, can't find MSYS2 Pacman database, I think something changed there too. Please take a look.

**Comment by jtanx** [comment]
Yes, I already have - https://github.com/fontforge/fontforge/pull/4664#issuecomment-808063572

Just waiting to see how long it will take for the fix to flow on, if it's a couple of days then I'll just wait, otherwise I'll come up with something.

File: fontforge/svg.c (hunk 1 above)
Comment (frank-trampe) [reply fontforge/svg.c:1558]: Are we sure that this wouldn't mishandle some other valid input that begins with 0? I can't readily find whether the specification allows leading zeros in quantities, for example.

Comment (skef) [reply fontforge/svg.c:1558]: I believe SVG arcs always have the full argument set and given where it's placed this code can only be parsing the flags, which are supposed to always be zero or one.

Comment (frank-trampe) [reply fontforge/svg.c:1558]: Okay.

Comment (ctrlcctrlv) [reply fontforge/svg.c:1558]: Right, this only applies to a very narrow case, not every leading 0. These flags are always there, and repeated leading zeroes will still work.

**Comment by jtanx** [comment]
> Otherwise they can be considered part of one large integer.

How does this work? Do you mean that `strtol` is parsing commas as like a thousands separator or something? I thought these functions were wrapped in `switch_to_c_locale` calls. Otherwise we should use something like https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-strtoll

**Comment by ctrlcctrlv** [comment]
@jtanx The problem is that `0` and `1` are flags, and _no space is required after them_, however _the flags are mandatory_.

You cannot read the flag as a number with `strtol`, as if the discretionary space is missing, it will swallow up the following arguments.

`1035` is `(1, 0, 35)` and the flag must be read as a single byte.

**Comment by jtanx** [comment]
If that's the case, why do you need `skipcomma()` between the flags?

**Comment by ctrlcctrlv** [comment]
Because `1, 0, 35` is just as valid. All of these are valid:

* `1035`
* `1 0 35`
* `1, 0, 35`

**Comment by jtanx** [comment]
Right, I see. Odd!

**Comment by ctrlcctrlv** [comment]
I'll push some tests and merge this because of how confusing it is :-)
