### PR TITLE
Expand Stroke replacement

### LINKED ISSUE #495: Crash in fontforge-cygwin_2012_08_02: expand short lines
Expanding a (horizontal) line which is shorter than 1.0 unit
leads to a crash.  Test case attached, run over with

```
fontforge -lang=ff -c "Open($1); SelectAll(); ExpandStroke(64,1,1); Save($2);" crash-expand-short.sfd
```

(Do not know how to make an attachment.) Temporarily put to http://ilyaz.org/software/tmp/fontforge/crash-expand-short.sfd.

### LINKED ISSUE #552: Internal Error Message
I do get (multiple times) the following error message while importing some SVG file:

```
Internal Error:
    Some fragments did not join
    [OK]
```

Maybe those king of messages could be printed to the warnings window?

### LINKED ISSUE #1228: fontforge-cygwin_2014_01_04: ExpandStroke() crashes in presence of sharp (40° or such) angles, or nearby segments
Example SFD files are in https://gist.github.com/ilyaza/9108327

Run with
  fontforge -lang=ff -c "Open($1); SelectAll(); ExpandStroke(64,1,1,0,1); " unifont-mono-xa996.sfd
(likewise for the second file).  Gives a stack dump (non-debugging version here, so cannot decipher it.)

(Note that the second file, unifont-mono-xaa1c-aa1d.sfd, contains two glyphs.  Each one of them works OK separately from the other one.  Breaking a stroke into several ones at sharp angles works around the issue in the first file; in the second one, I
needed to break the stroke into straight segments to make the script finish normally.

[This is not a new regression; it also crashes with 2012 build of fontforge.]

Thanks,
Ilya

### LINKED ISSUE #1424: fontforge-cygwin_2012_08_02: Message: Some fragments did not join in uniA9C3
I was not paying attention before, but today I noticed the message

```
Internal Error:
Some fragments did not join in uniA9C3
```

Googling, I see that it is mentioned in a couple of bug reports of dependent packages, but not in FontForge mailing lists themselves.

If needed, I may try to provide a minimized example.

### LINKED ISSUE #2547: Some self-intersecting stroked SVG paths become broken on import
Some self-intersecting SVG paths don't import properly. Depending on the particular shape of the stroke (and minor changes seem to make a difference) it can break apart in the general area where it self-intersects. It happens both with near-perpendicular and near-parallel selfoverlaps, and with some in between. It doesn't seem to matter whether the self-overlap is "clockwise" or "counter-clockwise".

This doesn't seem to be inherent to SplineSetStroke, because I cannot for the life of me manage to cause such behavior with the "Expand Stroke..." function in the GUI. Perhaps buggy parameters are being set somewhere.

(By the way, the generated outline's directions are all backwards. Using the "Expand Stroke..." function in the GUI gives the right direction. Maybe this is relevant?)

The following SVG data exhibits this bug:

```
<svg width="109" height="109" viewBox="0 0 109 109">
    <g style="fill:none;stroke:#000000;stroke-width:3;">
        <path d="M 20.328983,83.78678 C 150.51815,19.632996 -50.48081,26.082124 86.805084,86.093221"/>
    </g>
</svg>
```

It doesn't seem to matter whether I do it via python or via GUI's "import".

My copy of fontforge is "Based on sources from 23:20 UTC 28-Sep-2015-ML-D."

### LINKED ISSUE #3239: FontForge-2017-07-31-Windows-r2 “Expand stroke”: a minor modification leads to major effect
With the attached font, I do Ctrl-Shift-E (Expand Stroke) on the glyph for `M` (choosing `Round line cap`).  Here is what happens:

clip-m-pre  clip-m-post

There ***is*** a difference in how two tips are constructed (the letter is not symmetric), but the actual difference in the stroke should be of order of (I think) 0.1%.  However, one line join is very different from the other.

- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

[unifont.massaged_1_222_M-n.sfd.txt](https://github.com/fontforge/fontforge/files/1583982/unifont.massaged_1_222_M-n.sfd.txt)

### LINKED ISSUE #3240: FontForge-2017-07-31-Windows-r2: lock down on “Expand stroke”
[unifont.massaged__1_222-W.sfd.txt](https://github.com/fontforge/fontforge/files/1583994/unifont.massaged__1_222-W.sfd.txt)

Doing “Expand Stroke” (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>E</kbd>) on the attached file completely locks `fontforge`.  The only way out is to kill the process.

- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### LINKED ISSUE #3242: FontForge-2017-07-31-Windows-r2 “Expand stroke”: a minor modification leads to errors
This is very similar to #3239, only now the glyph is made symmetric.  Running “Expand stroke” now leads to an error: `Internal error: some fragments did not join`.

The generated glyph is not closed: there are two gaping holes on top.

- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

[unifont.massaged__1_224-M.sfd.txt](https://github.com/fontforge/fontforge/files/1584050/unifont.massaged__1_224-M.sfd.txt)

### LINKED ISSUE #3264: FontForge-2017-07-31-Windows-r2 “Expand Stroke”: Internal Error: Some fragments did not join in uni071B
Instructions: load the attached file, do <kbd>Ctrl</kbd>-<kbd>A</kbd>, <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>E</kbd>.  Set `64.3×64.3,   Line Cap=Round,  Remove internal contour`
and start the operation.

All the glyphs in the attached `.sfd` file show the error above.  (This is, actually, an update to obsolete #1424.)

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

[filt-unifont-mono-x0.sfd.txt](https://github.com/fontforge/fontforge/files/1799159/filt-unifont-mono-x0.sfd.txt)

### LINKED ISSUE #3718: Towards a replacement to the «Expand Stroke…» function
I, and others, have reported many Expand Stroke bugs, which no one seems to know how to fix. (For example, #3694, #3264, #3242, #3240, etc.)

Expand Stroke bugs are rarely ever fixed. I hope @skef doesn't hope me quoting him in some private correspondence to help make my point:

> I'm wary of [Expand Stroke]. It seems like GW approached a lot of the tricker spline code by tinkering **rather than drawing on theory or established algorithms.** I stared at #3432 for a while (for example) after finding that non-termination condition and still don't have much of an idea of how the algorithm is supposed to work

@skef is much better at B&eacute;zier spline math than I am, so if he doesn't understand how GW's algorithms work, I stand no chance of doing so.

The function is also aging, and to think that we could extend it is dubious at best. For example, we might want to make it so that you could vary the width of points along the spline as is possible with the width tool in e.g. Illustrator or via multiple plugins (Letterink, etc) to Glyphs.app or in Inkscape via &laquo;[Power Stroke](https://graphicdesign.stackexchange.com/questions/117822/stroke-width-tool-equivalent-in-inkscape)&raquo;.

My questions are:
* What &ldquo;established algorithms&rdquo; would help the situation?
  * Perhaps [InkScape's](https://gitlab.com/inkscape/inkscape/blob/master/src/livarot/PathStroke.cpp), which seems very Robust? Perhaps [Noodler's](https://github.com/mekkablue/Noodler/blob/master/Noodler.glyphsFilter/Contents/Resources/plugin.py), used by Glyphs.app? Something else I'm not aware of?
* Is it even possible to replace the «Expand Stroke…» dialog wholesale? 
  * Obviously at first we'd want to have them side-by-side until we replicated all the functionality.

### LINKED ISSUE #3762: ⟦Expand Stroke⟧ Rectangular (calligraphic) results in spline with strange looking rectangular cut-out
# A bug in three acts

2019-07-05-175620_1807x665_scrot
2019-07-05-175605_1814x693_scrot
2019-07-05-175555_1757x647_scrot

# Test case *sans* background image

[S.zip](https://github.com/fontforge/fontforge/files/3362127/S.zip)

## Required settings

# Work arounds

Attempting a &laquo;Simplify&raquo; _does not work_.

Enabling Spiro, moving the first point 1px to the left then 1px back (to force the original Bezier to be lost), then disabling Spiro again and stroking the resulting B&eacute;zier which now has many more points _does work_, but is very hacky obviously.

2019-07-05-180149_632x563_scrot
2019-07-05-180204_645x799_scrot

### LINKED ISSUE #3777: ⟦Expand Stroke⟧ Simple loop doesn't stroke correctly
This loop strokes in two pieces, one would be expected.
 | 

# Test case

## Required files
[loop.zip](https://github.com/fontforge/fontforge/files/3381394/loop.zip)

# Friendly warning

I'm still working on my lib2geom replacement for our &laquo;Expand Stroke&raquo;, the same path works in Inkscape so that will fix this when it's done. However, of course I'd be happy if the legacy stroker is fixed so am reporting this new bug I found.

### PR DESCRIPTION
**Pull request by skef**
Welcome `fontforge-user`s! The changes to the system are documented [here](https://raw.githack.com/fontforge/fontforge/7fb4ebdff4fc69b0281fd66707d1da5f1c34be48/doc/html/stroke.html). Follow the links in the first section to see the updated Python and native APIs.

---

This request is to merge the `stroke` branch into master, which will replace the Expand Stroke facility. 

As I am opening this the changes are *not* quite ready to be merged, even if there were no objections. I still need to add images to the new document and should add more specific tests. Even so, I believe the functionality of the replacement as I create this request includes all aspects of the current system and a number of new features, and is also more stable.  

In any case, the magnitude of the change is large enough that it is now time to get more eyes on the code and input into what else needs to change and how to test it. 

I expect I will make many of whatever additional changes are needed myself. However, I want to organize the discussion (and, with luck, some of the edits) the same way as the abandoned menus-2019 project. Therefore, I request that anyone who has a specific proposal for a change should either:

1. File a separate *issue*, tagged with the "stroke" label, with a description of and reasons for the change, or
2. File a *pull request* with the code for the change against the `stroke` branch (**not** the `master`). These should also get the "stroke" label.

This issue is therefore the place for general discussion, to ask questions about the new code, and to evaluate the ongoing quality of the `stroke` branch as changes are merged into it. I "reserve the right" to move aspects of the discussion into separate issues when necessary (or when I feel like it). 

The main places to look are:

1. `fontforge/splinestroke.c` and `fontforge/splinestroke.h`
2. `doc/html/stroke.html` (a document describing the system and its parameters.)
3. `fontforgeexe/cvstroke.c` (the UI changes)
4. `fontforge/python.c` and `doc/html/python.html` (the new python interface (which includes the legacy interface)
5. `fontforge/scripting.c` and `doc/html/scripting-alpha.html` (the new variant of ExpandStroke for the native scripting language)

Some other structural notes:

I added `utanvec.c` and `utanvec.h`, which contain slope-related code. 

I moved the spline fitting code into `splinefit.c` and `splinefit.h`, and extended it a little. `git blame` still works as long as you add `-C`. It takes a little longer but not too much. 

@ctrlcctrlv has been evaluating earlier versions of this code for a while now. 

Closes #3777 
Closes #3762 
Closes #3718 
Closes #3264 
Closes #3242
Closes #3240
Closes #3239 
Closes #2547 
Closes #1424 
Closes #1228 
Closes #552
Closes #495

### CODE REVIEW

**Comment by skef** [comment]
First some high-level stuff:

The old system had three implementations, while the new system has a single implementation. They have very little in common. Most importantly the old system attempted to do line removal (broadly speaking) in advance using a quasi-image. The new system just draws the contours, cusps and intersections and all, and then has Remove Overlap deal with removing those. So at a high level, what happens with each contour is:

1. Each general offset curve is calculated, cusps and all, adding in the selected joins along the way.
2. If the source contour is open, the two offsets are closed with caps. Each offset is closed separately with a join.
3. All the stroked contours are collected together in a SplineSet, and Remove Overlap is run on all of them at once. (There are parameters to run Remove Overlap on a per-contour basis or not to run it at all.) 
4. Add Extrema and Simplify are run in that order (unless the parameters say not to).

I should admit that I did not think this was going to be how the final system worked, because while I knew Remove Overlap would handle the "simple" cases I thought you would see "cusp interference" and such in more complex cases. However, it has turned out to very difficult to come up with a case that the non-zero rule doesn't handle. There have been a few cases that came up where Remove Overlap produces the wrong result, but these look correct when skipping that step and viewing the cusp-speckled splines in Preview. (Some of those cases are recorded in #3950, but I don't think the current code is generating the problematic patterns as frequently as it was when I filed that.)

**Comment by skef** [comment]
Now the most important conceptual nitty-gritty:

**Polygonal offsetting** 

Suppose you attach one pen to another in a way that preserves the distance and angle between them. Then what you write with one pen is traced by the other, as with the polygraph famously used (but not invented) by Thomas Jefferson. The corner of a polygonal nib is like this: it just duplicates the portion of the spline it traces at an offset.

The only "trick" with a polygonal nib, therefore, is determining which one is "tracing the spline". But this is pretty simple: There is a line going into the point at a certain angle and one leaving the point at a certain angle. The point will trace the line when the spline being traced is between those angles. (It's actually a bit more complicated than that, because you have to deal with the "left" and "right" contours, each of which will be traced by a point on (roughly) the opposite side of the nib, but those are just details.)

So now you can determine which point traces the line, and when you need to switch: you look for the angles of the lines of the polygon. How do you switch? To simplify, a switch is either "backward" or "forward" (relative to the tracing direction). In either case you can just draw a line between the old and new offsets. A backward line will result in a self-intersection of that side of the spline, analogous to a cusp. This will need to be removed later. A forward line will appear on the contour edge *assuming it isn't covered by some double-back in the traced curve later). 

**Circular offsetting**

Offsetting with a circular nib is easier in most ways. You look at the tangent angle of the traced contour at the current point (t-value), calculate the normal and the point will be *r* away in that direction. Unfortunately curved nib doesn't duplicate the curve, it "expands" it on one side and "scrunches" it on the other, depending on the curvature of the traced contour. If it scrunches too much you get a "cusp": the direction reverses and therefore the shape inverts. (Formally this happens when the curvature of the traced contour is tighter than the curvature of the nib.) 

There are fudges to deal with shape change without having to fit points, but the old code uses fitting and I also just fit the splines to "enough" points (which is easy as long as you are careful to only fit smooth curves and make careful use of known slope angles).

**General offsetting**

What about generalizing the two? Suppose you restrict the potential shapes to *convex* nibs. For every convex nib each tangent angle maps to exactly one point on the edge of the nib. If the nib is entirely curved the mapping will be 1:1. If there are sharp corners then a range of tangent angles will map to the same point. If the nib shape is modeled as a cubic contour you can make a list of angle ranges, where each range is associated with either a spline curve or a spline point. The point-assigned ranges work just polygonal nib points. The others work sort of like circular nibs, but you need to do more work.

What work? You first need to find the t value on the spline associated with the specific angle of interest. There is an easy closed form for that: rotate the spline by that angle, solve for extrema, and eliminate any false-positives. Then you calculate the x,y value corresponding to t, and that gives you your offset, which you use instead of the radius/normal calculation. 

Everything else is details.

**Comment by skef** [comment]
Oh, you may find this handy:

[nibs.zip](https://github.com/fontforge/fontforge/files/3779099/nibs.zip)

Stick `Nibs.py` in your python contrib directory and `nibs.P` in your FontForge "user config" directory. This will add a Tools menu making it easier to copy and set general convex nibs.

**Comment by skef** [comment]
Interesting -- the main stroke tests are in test1003.py, and it looks like that didn't complete on AppVeyor (or at least it isn't in the list). But it works in my testing and in (most of the?) other builds.

**Comment by ctrlcctrlv** [comment]
I've been building and testing this code for months as @skef has improved it and I can say that it is:

1. amazing
2. _way better_ than the current stroke code
3. solves all my broken test cases as @skef notes
4. is very fast! like orders of magnitude faster. milliseconds compared to minutes on some inputs

I wholeheartedly approve merging it once the builds pass.

**Comment by skef** [comment]
About the automated builds: Of the four Travis builds, three succeeded and "LINUX_RELEASE=true BINTRAY_DEPLOY=true" failed. However, on my reading of the log that build seemed to poop out after all tests succeed, so the failure seems spurious. 

Appveyor looks more suspicious, in that it appears the main splinestroke tests never finished, or were never reported finished. But I can't tell anything beyond that -- someone will have to take a look.

File: fontforge/splineutil.c [hunk 1]
```diff
@@ -2202,6 +2211,21 @@ SplinePointList *SPLCopyTransformedHintMasks(RefChar *r,
...
 
+void SplinePointListClearCPSel(SplinePointList *spl) {
+    Spline *spline, *first;
+
+    for ( ; spl!=NULL; spl = spl->next ) {
+	first = NULL;
+	spl->first->nextcpselected = false;
+	spl->first->prevcpselected = false;
+	for ( spline = spl->first->next; spline!=NULL && spline!=first; spline=spline->to->next ) {
+	     spl->first->nextcpselected = false;
```
Comment (jtanx) [inline fontforge/splineutil.c]: For all that this iterates the spline set, isn't this always only updating the first spline point, as spl isn't updated in the inner loop?

File: fontforge/utanvec.c [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+#include <fontforge-config.h>
+
+#include "utanvec.h"
+#include "splineutil.h"
+#include "splineutil2.h"
+
+#include <math.h>
+#include <assert.h>
+
+#define PI      3.1415926535897932 // For tests
```
Comment (jtanx) [inline fontforge/utanvec.c]: We have many variants of this floating around, we should clean this up

**Comment by jtanx** [comment]
On the Windows tests, it's failing an assertion:

```
tanjj@fuse MINGW32 ~/ffbuild/work/mingw32/fontforge/build
$ctest -V -R test1003
UpdateCTestConfiguration  from :C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/DartConfiguration.tcl
Parse Config file:C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/DartConfiguration.tcl
Parse Config file:C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/DartConfiguration.tcl
Test project C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 64
    Start 64: test1003_py

64: Test command: C:\msys64\home\tanjj\ffbuild\work\mingw32\fontforge\build\bin\systestdriver.exe "--mode" "py" "--binary" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/bin/fontforge.exe" "--script" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py" "--exedir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/bin" "--libdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/lib" "--argdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/tests/fonts" "--argdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/fonts" "--desc" "Various stroke tests" "StrokeTests.sfd"
64: Test timeout computed to be: 1500
64: Test C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py(mode=py): Various stroke tests
64: Running: C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/bin/fontforge.exe -lang py -script C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/fonts\StrokeTests.sfd
64: Copyright (c) 2000-2019. See AUTHORS for Contributors.
64:  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
64:  with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
64:  Version: 20190801
64:  Based on sources from 2019-10-12 23:32 UTC-ML-TtfDb-D-GDK3.
64:  Based on source from git with hash: d57208b8b6da9fde9ac6f531a49e8c0d99039cd0
64: Assertion failed: 0, file ../fontforge/splinestroke.c, line 319
64: PythonUI_Init()
64: copyUIMethodsToBaseTable()
64: Test C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py failed with exit code 3
1/2 Test #64: test1003_py ......................***Failed    0.20 sec
test 65
    Start 65: test1003_pyhook

65: Test command: C:\msys64\home\tanjj\ffbuild\work\mingw32\fontforge\build\bin\systestdriver.exe "--mode" "pyhook" "--binary" "C:/msys64/mingw32/bin/python3.7.exe" "--script" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py" "--exedir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/bin" "--libdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/lib" "--argdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/build/tests/fonts" "--argdir" "C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/fonts" "--desc" "Various stroke tests" "StrokeTests.sfd"
65: Test timeout computed to be: 1500
65: Test C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py(mode=pyhook): Various stroke tests
65: Running: C:/msys64/mingw32/bin/python3.7.exe -Ss C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/fonts\StrokeTests.sfd
65: Assertion failed: 0, file ../fontforge/splinestroke.c, line 319
65: Test C:/msys64/home/tanjj/ffbuild/work/mingw32/fontforge/tests/test1003.py failed with exit code 3
2/2 Test #65: test1003_pyhook ..................***Failed    0.16 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.40 sec

The following tests FAILED:
         64 - test1003_py (Failed)
         65 - test1003_pyhook (Failed)
Errors while running CTest

```

**Comment by skef** [comment]
> On the Windows tests, it's failing an assertion:
>
> `Assertion failed: 0, file ../fontforge/splinestroke.c, line 319`

OK that's *weird*. 

`SplineContourOuterCCWRemoveOverlap()` is a hack to clean up artifacts from isolated counter-clockwise splines. It builds a rectangle around it, runs SplineSetRemoveOverlap(), and then looks for the contour it built to remove it. You hit the assert(0) in that function when you don't find the added contour afterward. 

I have no idea why that would be happening only on Windows. The thing to do, and which I could do if I can get some kind of Windows debugging access and reproduce, is to examine the spline set at the assert point to figure out how its different.

**Comment by jtanx** [comment]
Also just adding, I recompiled in release mode, and the reason why appveyor doesn't show anything else is apparently it gets stuck in some sort of infinite loop and never finishes that test. Time to break out gdb...

File: fontforge/utanvec.c (hunk 2 above)
Comment (skef) [reply fontforge/utanvec.c]: The `PI`s or slope abstractions? 

I'm happy to go through and clean up the PIs. I would be less confident about the slopes.

Comment (jtanx) [reply fontforge/utanvec.c]: PI, if you grep for 3.1415 you'll find many references

**Comment by skef** [comment]
I'll try a release build and see if I can reproduce. Maybe something important wound up in an assert somehow.

**Comment by jtanx** [comment]
My guess is because something is invoking UB.

It'd help if we added `-Wall` for new code to catch obvious issues. Also probably about time we sort out some code style for new code.

**Comment by skef** [comment]
Release build on Arch passes tests fine. 

I'll ask this once, just in case: test1003.py used to take the longest time and didn't run under pyhook for that reason. It now takes under a second. Could there have been some check/built in expectation/etc. having to do with the time of that test that is interfering now?

**Comment by jtanx** [comment]
Regarding the built-in check, none that I'm aware of.

I can repro by directly calling the test case. Seems to spend most of the time here:

```
(gdb) thread 1
[Switching to thread 1 (Thread 6184.0x454)]
#0  IterateSplineSolve (sp=sp@entry=0x5257d78, tmin=0.72603222758967167, tmin@entry=0.72602804710943347, tmax=440.0433203911353, tmax@entry=358.8450750216835,
    sought=sought@entry=358.8450750216835) at ../fontforge/splineutil.c:3670
3670                if ( t==tmax || t==tmin )
(gdb) bt
#0  IterateSplineSolve (sp=sp@entry=0x5257d78, tmin=0.72603222758967167, tmin@entry=0.72602804710943347, tmax=440.0433203911353, tmax@entry=358.8450750216835,
    sought=sought@entry=358.8450750216835) at ../fontforge/splineutil.c:3670
#1  0x01e66b7f in IterateSplineSolveFixup (sp=0x5257d78, tmin=0.72602804710943347, tmax=<optimized out>, sought=sought@entry=358.8450750216835) at ../fontforge/splineutil.c:3699
#2  0x01e3e262 in FindMonotonicIntersection (m2=0x5258070, m1=0x49d8dd8) at ../fontforge/splineoverlap.c:1822
#3  FindIntersections (ms=<optimized out>, ms@entry=0x49d8d38, ot=ot@entry=over_remove) at ../fontforge/splineoverlap.c:2341
#4  0x01e417ce in SplineSetRemoveOverlap (sc=sc@entry=0x0, base=base@entry=0x49afdb8, ot=ot@entry=over_remove) at ../fontforge/splineoverlap.c:4002
#5  0x01e5e30a in SplineSetStroke (ss=<optimized out>, si=<optimized out>, si@entry=0x144f410, order2=<optimized out>) at ../fontforge/splinestroke.c:1952
#6  0x01e5e528 in FVStrokeItScript (_fv=0x5257390, si=si@entry=0x144f410, pointless_argument=pointless_argument@entry=0) at ../fontforge/splinestroke.c:1993
#7  0x01dc16e0 in PyFFFont_Stroke (self=0x522a4a0, args=0x520c84c, keywds=0x0) at ../fontforge/python.c:17718
#8  0x6267d7eb in libpython3.7m!_PyMethodDescr_FastCallKeywords () from C:\msys64\mingw32\bin\libpython3.7m.dll
#9  0x05233628 in ?? ()
#10 0x05233628 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

I'll recompile in non-release mode and see what's going on at the assertion

File: fontforge/splineutil.c (hunk 1 above)
Comment (skef) [reply fontforge/splineutil.c]: Yeah, I borked my copy of `SplinePointListSelect()`.

**Comment by skef** [comment]
Oh, I misunderstood that there was a debug assertion and a release infinite loop. I'll just let you investigate and work on `PI`. 

I didn't touch the RemoveOverlap code and for the most part it's been working quite well.

**Comment by jtanx** [comment]
```
(gdb) p b
$5 = {minx = -14.289249183028012, maxx = 1070.6391958351867, miny = -110.1920000
0000001, maxy = 591.32656476660873}
```

I think I know what it is. The Windows build is 32 bit, and so it's probably making use of 80-bit floats on intermediates, or something like that. Whereas everything else is 64-bit and probably making use of SSE. Basically with something like this:

```
double ba=b.minx-100;
printf("%d\n", ba==(b.minx-100));
```

You get `0` (i.e. comparing against the intermediate is not equivalent). Doing something like this

```diff
diff --git a/fontforge/splinestroke.c b/fontforge/splinestroke.c
index b4e4ff3bc..9290fb3b2 100644
--- a/fontforge/splinestroke.c
+++ b/fontforge/splinestroke.c
@@ -292,22 +292,26 @@ static SplineSet *SplineContourOuterCCWRemoveOverlap(SplineSet *ss) {
     SplineSet *ss_tmp, *ss_last = NULL;

     SplineSetQuickBounds(ss,&b);
+    b.minx -= 100;
+    b.miny -= 100;
+    b.maxx += 100;
+    b.maxy += 100;
+
     ss_tmp = chunkalloc(sizeof(SplineSet));
-    ss_tmp->first = SplinePointCreate(b.minx-100,b.miny-100);
-    ss_tmp->last = SplinePointCreate(b.minx-100,b.maxy+100);
+    ss_tmp->first = SplinePointCreate(b.minx,b.miny);
+    ss_tmp->last = SplinePointCreate(b.minx,b.maxy);
     SplineMake3(ss_tmp->first, ss_tmp->last);
-    sp = SplinePointCreate(b.maxx+100,b.maxy+100);
+    sp = SplinePointCreate(b.maxx,b.maxy);
     SplineMake3(ss_tmp->last, sp);
     ss_tmp->last = sp;
-    sp = SplinePointCreate(b.maxx+100,b.miny-100);
+    sp = SplinePointCreate(b.maxx,b.miny);
     SplineMake3(ss_tmp->last, sp);
     SplineMake3(sp, ss_tmp->first);
     ss_tmp->last = ss_tmp->first;
     ss->next = ss_tmp;
     ss=SplineSetRemoveOverlap(NULL,ss,over_remove);
-    for ( ss_tmp=ss; ss_tmp!=NULL; ss_last=ss_tmp, ss_tmp=ss_tmp->next )
-       if (   ss_tmp->first->me.x==(b.minx-100)
-           || ss_tmp->first->me.x==(b.maxx+100) ) {
+    for ( ss_tmp=ss; ss_tmp!=NULL; ss_last=ss_tmp, ss_tmp=ss_tmp->next ) {
+       if (   ss_tmp->first->me.x==b.minx || ss_tmp->first->me.x==b.maxx ) {
            if ( ss_last==NULL )
                ss = ss->next;
            else
@@ -316,6 +320,7 @@ static SplineSet *SplineContourOuterCCWRemoveOverlap(SplineSet *ss) {
            SplinePointListFree(ss_tmp);
            return ss;
        }
+    }
     assert(0);
     return ss;
 }

```

The assertion goes away.

I do get this in the output, but not sure if that's expected:

```
Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 2019-10-29 08:43 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: c6d8488a006103808c079912035756189c9f30b9
PythonUI_Init()
copyUIMethodsToBaseTable()
triangle
square
pentagon
circular
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
caligraphic
Internal Error (overlap): Winding number did not return to 0 when y=-1.83838
Internal Error (overlap): Winding number did not return to 0 when y=-1.83838
Internal Error (overlap): monotonic is both needed and unneeded (241.716,-1.83838)->(230.284,-24.1616). y=-1.83838 (prev=-10.5)
Internal Error (overlap): monotonic is both needed and unneeded (262.583,-18.111)->(275.716,3.16162). y=-1.83838 (prev=-35.0253)
Internal Error (overlap): monotonic is both needed and unneeded (382.193,57.939)->(264.293,-19.1603). y=-1.83838 (prev=-10.5)
Internal Error (overlap): Winding number did not return to 0 when y=-1.83838
Internal Error (overlap): Humph. This monotonic leads nowhere (129.175,25.3952)->(236.716,-2.83838).
Internal Error (overlap): couldn't find a needed exit from an intersection
Internal Error (overlap): couldn't find a needed exit from an intersection
```

**Comment by jtanx** [comment]
It still loops infinitely on the release build though, so there's probably more of that somewhere else. And that's all I have time to test for now.

**Comment by skef** [comment]
> I do get this in the output, but not sure if that's expected:

Let's just say it's not unexpected. Those messages are common when Remove Overlap still manages to do its job. 

You can always quickly edit the test to save the output and then check out the files. Errors usually aren't that subtle.

**Comment by skef** [comment]
Hmm. Github is behaving strangely with my attempts to make a pull request against the stroke branch.

**Comment by jtanx** [comment]
Ok, actually just a bit more info before I stop:

It's stuck in this loop:
https://github.com/fontforge/fontforge/blob/f083abdd3fb7d507e82a5dd5676b0476e36883d9/fontforge/splineoverlap.c#L1797-L1798

If I print the diff after this line: https://github.com/fontforge/fontforge/blob/f083abdd3fb7d507e82a5dd5676b0476e36883d9/fontforge/splineoverlap.c#L1774

I get:

```
triangle
diff 5.67957368861351419, b.maxy:540.591433057316067, b.miny:358.845075021683613
diff 3.66120521695887291, b.maxy:695.25, b.miny:578.091433057316067
diff 5.66355340011697095, b.maxy:358.845075021683499, b.miny:177.611366217940429
diff 3.55271367880050093e-15, b.maxy:358.845075021683613, b.miny:358.845075021683499
```

**Comment by skef** [comment]
Happily, GitHub is apparently smart enough to print the ref number and description next to a commit merged via another pull request. So when reviewing "here" you can refer to the other issues as needed.

**Comment by skef** [comment]
@ilyaza if you are still using FontForge this might interest you.

**Comment by frank-trampe** [comment]
@jtanx, is `x` not moving in the overlap code, or is something else jamming?

**Comment by jtanx** [comment]
I turned up compiler warnings, and these sound like the likely candidates:

```
../fontforge/splineoverlap.c: In function 'FindIntersections':
../fontforge/splineoverlap.c:1907:30: warning: 't2o' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1907 |   y2o = ((m2->s->splines[1].a*t2o+m2->s->splines[1].b)*t2o+m2->s->splines[1].c)*t2o+m2->s->splines[1].d;
      |           ~~~~~~~~~~~~~~~~~~~^~~~
../fontforge/splineoverlap.c:1889:23: note: 't2o' was declared here
 1889 |   extended t1,t2, t1o,t2o/*, t1t,t2t*/ ;
      |                       ^~~
../fontforge/splineoverlap.c:1906:80: warning: 't1o' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1906 |   y1o = ((m1->s->splines[1].a*t1o+m1->s->splines[1].b)*t1o+m1->s->splines[1].c)*t1o+m1->s->splines[1].d;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../fontforge/splineoverlap.c:1889:19: note: 't1o' was declared here
 1889 |   extended t1,t2, t1o,t2o/*, t1t,t2t*/ ;
      |                   ^~~
../fontforge/splineoverlap.c:1792:80: warning: 't2o' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1792 |   x2o = ((m2->s->splines[0].a*t2o+m2->s->splines[0].b)*t2o+m2->s->splines[0].c)*t2o+m2->s->splines[0].d;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../fontforge/splineoverlap.c:1771:23: note: 't2o' was declared here
 1771 |   extended t1,t2, t1o,t2o/*, t1t,t2t */;
      |                       ^~~
../fontforge/splineoverlap.c:1791:80: warning: 't1o' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1791 |   x1o = ((m1->s->splines[0].a*t1o+m1->s->splines[0].b)*t1o+m1->s->splines[0].c)*t1o+m1->s->splines[0].d;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../fontforge/splineoverlap.c:1771:19: note: 't1o' was declared here
 1771 |   extended t1,t2, t1o,t2o/*, t1t,t2t */;

```

With
```
diff: 3.55271367880050093e-15, min: 358.845075021683499, max: 358.845075021683613
```

Note that min>max, so `while ( y<b.maxy ) {` is false (where `y=b.miny`), and so `t1o` and `t2o` are uninitialised.

**Comment by skef** [comment]
> I turned up compiler warnings

If I wanted to do the same temporarily for `splinestroke.c` is there a quick solution?

**Comment by skef** [comment]
Never mind -- figured out an easy way.

**Comment by skef** [comment]
It may make sense to add some fixes (e.g. to Remove Overlap) into the master directly, and there will probably be other miscellaneous changes while this is being worked on.

I guess the best way to handle that is to try to merge all the viable outstanding PRs into the `stroke` branch, and then I can rebase everything off the master and force-update the contents. Not ideal but should be OK.

**Comment by jtanx** [comment]
Well the spline overlap issue is probably the same as #527, and fixing it would probably fix #529 too.

#527 made `x` volatile but not `y`. Making `y` volatile fixes it for me. Having said that, maybe it should just be changed to work in ulps instead...

**Comment by skef** [comment]
As I was writing this replacement I tried to maintain as much precision as possible through the calls, not so much because I was convinced someone would need it but so that I could make comparisons and assertions well below anything that would wind up being visual. (This practice falls down between smooth splines because of rounding, hence INTERSPLINE_MARGIN and INTRASPLINE_MARGIN.)

One consequence is that the code turns up bugs, or limitations, in other code that are difficult to communicate without this code available. Often the SFD doesn't store with enough precision to reproduce, so unless you can run the algorithm you have to resort to loading values via python, which is a pain. 

However, I don't think any of the inaccuracy bugs (as opposed to crashes, non-terminating loops and so forth) need to be fixed prior to merging. They're already there and the new Simplify/Add Extrema/Remove Overlap parameters will make it much easier to discuss them. 

(I know there are Add Extrema problems, I've filed one Remove Overlap geometry bug; with Simplify it may be more a matter of it not doing all that one hopes it would, or my not knowing how to call it.)

File: fontforge/python.c [hunk 3]
```diff
@@ -1142,6 +1140,16 @@ static PyObject *PyFF_GetScriptPath(PyObject *UNUSED(self), PyObject *UNUSED(arg
     return ret;
 }
 
+static PyObject *PyFF_GetUserConfigPath(PyObject *UNUSED(self), PyObject *UNUSED(args)) {
+    PyObject *ret;
+    const char *userdir;
+
+    userdir = getFontForgeUserDir(Config);
```
Comment (jtanx) [inline fontforge/python.c]: This needs to be freed

File: fontforge/python.c [hunk 4]
```diff
@@ -1596,6 +1604,82 @@ Py_RETURN_NONE;
 return( reto );
 }
 
+int NibCheck(SplineSet *ss);
+
+int PyFF_ConvexNibID(char *tok) {
+   int r = ConvexNibID(tok);
+   if ( r==-1 )
+	PyErr_Format(PyExc_TypeError, "Unrecognized convex nib context name" );
```
Comment (jtanx) [inline fontforge/python.c]: I haven't checked anywhere else in this file but do we make these translatable elsewhere?

File: fontforge/python.c [hunk 5]
```diff
@@ -1596,6 +1604,82 @@ Py_RETURN_NONE;
...
+
+    PYGETSTR(args, tok, NULL);
+    toknum = PyFF_ConvexNibID(tok);
+    ENDPYGETSTR();
+    if ( toknum==-1 )
+	return NULL;
+
+    ss = StrokeGetConvex(toknum, false);
+    if ( ss==NULL )
+	Py_RETURN_NONE;
```
Comment (jtanx) [inline fontforge/python.c]: Seems kind of inconsistent how `return NULL` is used elsewhere then this macro is used here

**Comment by skef** [comment]
> It may make sense to add some fixes (e.g. to Remove Overlap) into the master directly, and there will probably be other miscellaneous changes while this is being worked on.

My faltering brain didn't put together that we'll just get anything non-conflicting automatically as the master changes. Please forgive my getting-over-the-hump-anxiety babbling in this thread.

File: fontforge/python.c [hunk 6]
```diff
@@ -4367,121 +4427,199 @@ struct flaglist strokeflags[] = {
...
+		return( -1 );
+	    }
 	}
-	si->stroke_type = si_std;
-    } else if ( strcmp(str,"caligraphic")==0 || strcmp(str,"square")==0 ) {
-	if ( !PyArg_ParseTuple(args,"sddd|O", &str, &width, &minor, &angle, &flagtuple ) ) {
-	    ENDPYGETSTR();
-return( -1 );
+    } else if (    strcmp(str, "calligraphic")==0
+                || strcmp(str, "caligraphic")==0
```
Comment (jtanx) [inline fontforge/python.c]: oof

File: fontforge/splinefit.c [hunk 7]
```diff
@@ -0,0 +1,1067 @@
+/* -*- coding: utf-8 -*- */
```
Comment (jtanx) [inline fontforge/splinefit.c]: For my understanding, is there any actual new code in this file, or is it just a straight copy out? If it's not a straight copy, what's new?

File: fontforge/splinestroke.c [hunk 8]
```diff
@@ -32,3689 +32,1805 @@
...
-/*  drawn counter clockwise */
-struct extrapoly {
-    BasePoint poly[4];
-    int ptcnt;		/* 3 (for miters) or 4 (for square caps) */
-};
+#define CIRCOFF 0.551915
 
-enum pentype { pt_circle, pt_square, pt_poly };
+// Rounding makes even slope-continuous splines only approximately so.
+#define INTERSPLINE_MARGIN (1e-1)
```
Comment (jtanx) [inline fontforge/splinestroke.c]: I am guessing these only make sense if we use doubles? Probably more reason to just enforce that doubles are always used and get rid of the configuration option.

File: fontforge/splinestroke.c [hunk 9]
```diff
@@ -32,3689 +32,1805 @@
...
-	}
-    }
-    if ( !isend )
-	c->all[c->cur++] = done;
+StrokeInfo *InitializeStrokeInfo(StrokeInfo *sip) {
+    if ( sip==NULL )
+	sip = malloc(sizeof(StrokeInfo));
+
+    *sip = (StrokeInfo) {
+        25.0,         // radius
```
Comment (jtanx) [inline fontforge/splinestroke.c]: Excuse my ignorance, but how do these get determined?

File: fontforge/python.c (hunk 4 above)
Comment (skef) [reply fontforge/python.c]: There could be some corner of the FF Python API that is I18Ned, but either the vast majority or all of it is not.

File: fontforge/python.c (hunk 5 above)
Comment (skef) [reply fontforge/python.c]: The way this stuff works is that returning a `NULL` means there's an error, while `Py_RETURN_NONE` marks a successful completion for which the python wrapper will return `None`. (Every python function call syntactically returns "something", even if it's just `None`.)

The reason the NULLs "work" here is that they are on conditions that set earlier errors. `PyFF_ConvexNibID()` for example only returns -1 after setting it's own error -- it's actually a wrapper to do just that.

File: fontforge/splinefit.c (hunk 7 above)
Comment (skef) [reply fontforge/splinefit.c]: Ah yes -- sorry. There could be some tiny changes above `_ApproximateSplineSetFromGen()` but basically everything above that function is a copy and those last two functions are new.

File: fontforge/splinestroke.c (hunk 8 above)
Comment (skef) [reply fontforge/splinestroke.c]: I pretty much used bigreal everywhere to represent the lack of thought I put into considering what could be lower precision. Getting real and bigreal cleanly separated after years of having both be double would be a mini-project at least, and this code would have to be some part of that project. 

However, on your narrow question, no: INTRASPLINE_MARGIN might well have to change, but INTERSPLINE_MARGIN has to do with int-rounding at smooth points, so it would continue to have that value.

File: fontforge/splinestroke.c (hunk 9 above)
Comment (skef) [reply fontforge/splinestroke.c]: There are five ways:

1. The radius default mostly serves as a CVStroke default. The other interfaces make you set it in cases where it will be used (i.e. pen types other than si_nib). 
2. The pen, cap and join defaults represent offsetting with round ends. This seems like a good general default behavior. 
3. The rest of the boolean, 0.0, and NULL values are "principled" defaults: there are options and these are the best initial choices. I actually added this function because I got tired of dealing with boolean conditions "phrased" so that false was default to work with memset(0).
4. A join limit of 20 corresponds to an SVG `stroke-miterlimit` of 20 and therefore a PostScript miterlimit of 10 (PS used stroke width, SVG uses offsetting radius). That's from the `c.miterlimit` assignment in the old `SplineSetStroke()`, as noted in the old comments. 
5. The accuracy target is my choice. I'm not sure I can defend it on principles so I'm open to suggestion and argument.

File: fontforge/splinefit.c (hunk 7 above)
Comment (skef) [reply fontforge/splinefit.c]: Oh, I guess I should take that back. 

There was an old structure called "TPoint" that had x, y, and t values and was used by a number of functions. I replaced that with a FitPoint structure that puts x and y into a BasePoint and adds a slope. Most functions that use TPoints were rewritten to use FitPoints while ignoring the slope. So while this winds up being mostly syntactic I can't honestly call it "tiny".

Comment (skef) [reply fontforge/splinefit.c]: The easiest method of review for that upper material is probably to make a local git clone and use blame -C on the file. I just tried this and it's pretty tractable.

File: fontforge/splinestroke.c (hunk 9 above)
Comment (skef) [reply fontforge/splinestroke.c]: Actually, with the lc_nib and lj_nib defaults it's arguably less relevant that the circular nib will have round caps and joins as that these are the appropriate defaults for all other nib types, given that the previous algorithm only had these options for rectangular and polygonal nibs. These are the options that correspond to what would happen if the nib were traced on paper.

**Comment by skef** [comment]
@jtanx: Thanks for the overlap fix! This passes the checks now.

File: fontforge/splinestroke.c [hunk 10]
```diff
@@ -32,3689 +32,1805 @@
...
+	                       s->from->nextcp, s->to->me, true) )
+		return Shape_BadCP;
+	    if ( !LineSameSide(s->to->me, s->to->prevcp,
+	                       s->from->nextcp, s->from->me, true) )
+		return Shape_BadCP;
+	    s->from->nextcpselected = false;
+	    s->from->selected = false;
+	    s->to->selected = true;
+	    s->to->prevcpselected = true;
+	    if ( LineSameSide(s->fro
```
Comment (jtanx) [inline fontforge/splinestroke.c]: Is this for debugging purposes?

Comment (jtanx) [inline fontforge/splinestroke.c]: Should this be `NDEBUG`?

I'm surprised the spurious semicolon doesn't trip some compiler warning

[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: I don't know where the pro/anti-switch wars stand now. I remember they were frowned on some years ago.

Comment (skef) [reply fontforge/splinestroke.c]: Yes, it should be NDEBUG. 

I thought the null statement was syntactically preferable to an empty loop.

Comment (skef) [reply fontforge/splinestroke.c]: Not exactly. 

Cusps never show up in the finished product -- they're always "under the nib" -- so there's no real reason to trace them accurately. However, I started out doing that anyway because it didn't affect the performance much and I figured someone might want to know the exact-ish cusp geometry. 

Unfortunately there's some weird issue with the fitting algorithm that always co-locates one control point at the start, eliminating the slope. This makes the curve both inaccurate and tends to confuse Remove Overlap. 

So I switched the code to just put a few points on the cusps but left the means there so that if someone wanted to go back and look at the tracing problem it was easy.

**Comment by skef** [comment]
> I'll try to take a closer look over the weekend, but I probably won't be able to go too in depth overall, there's a lot of code, some of it quite dense, in an area that I'm not overly familiar with.

The planned release is a long way off so I don't think there's any big hurry. The risk is more about mustering the review cycles at all, so to the extent you can help it's great. 

> I think you mentioned this earlier, but are you adding any further tests to the test suite?

The main regression test that's needed is validating the nib shape error checking. Then there should probably be some breadth on the various options, probably on a subset of StrokeTests.sfd. Those are pretty easy and I'll add them.

Unfortunately regression testing isn't of much use for testing correctness without some way to compare based on geometry. A pointwise comparison isn't useful and FontForge's contour comparison function is quite broken.

So I have been thinking it would be more useful if I adapted the approach I took in the PDF for https://github.com/alif-type/libertinus/pull/228 . Basically let someone run the old and new software and then compare glyph-by-glyph visually. That works well for identical options and not bad for others, as you can just verify the caps and joins are at least in the right categories and so forth.

File: fontforge/splinestroke.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (jtanx) [reply fontforge/splinestroke.c]: I didn't even know there was a war :P

**Comment by jtanx** [comment]
The expand stroke dialog is very tall now, it's near-on too tall to fit on my screen:
image

If I were using the fallback theme, it'd be even larger.

**Comment by skef** [comment]
The proper fix for the dialog is to eliminate the in-dialog editor. I know I've discussed this somewhere before but I can't find the link right now. Obviously that's an "intrusive" fix that would require thought and discussion about what would replace it. I'd rather put that off. 

Short of that, I suppose we could try to make the relative orientations of the editing area and the parameter area horizontal rather than vertical. Do you think that would be a good idea?

**Comment by skef** [comment]
Hmm. Another idea is to reduce the display aspect of the dialog to a shorter rectangle, make the nib type selectors vertical and move them up next to it, and move the editing functionality into a modal-on-modal dialog. 

I'll think about it.

**Comment by ilyaza** [comment]
@skef: I have no clue when I would have time to return to my font-stuff.

About your description of the architecture:

    * Polygonal: the description does not work for non-convex polygons.  I presume you preprocess non-convex cases into convex parts.

    * Polygonals: I could not find the desciption what to do do with corners/end-points of the contour.  For example, consider expanding a (connected) broken line made of one or two short straight segments with a complicated (convex) polygon.  The shape of the polygon matters in the corner points, and in the end-points.  (Again, decomposing the stroke into smooth parts reduces this situation to the need to consider end-points only.)

(Sorry if you mention these issues above; I read this thread very cursorily only!)

**Comment by skef** [comment]
@ilyaza:

In the description above I really meant "convex polygon" where I said "polygon". That's the same restriction as the existing system has. It verifies that the nib is convex based on rules that are described in the "General convex nibs" section of  

https://github.com/fontforge/fontforge/blob/7336dd6d373e488ad044152c0e90960dd845a271/doc/html/stroke.html

My description was misleading but (I hope) the documentation is clear on this subject, and I think it also addresses your two questions (although you might not be entirely pleased by the answers.) 

The reason I split the case into "round" and "polygonal" above was to describe the difference in an offset "drawn" by a point and one "drawn" by a curve. The system uses that distinction to support general convex nibs that have curves and "points" -- the latter being not just where lines meet but also where a curve transitions to a line or two curves transition non-smoothly. Below are the main nibs I use for testing because they have various tricky features. They give an idea of both the breadth of and restrictions on nib shapes:

nibs

There is a fairly easy way for the user to stroke with what might be called a "pseudo-concave nib" by using multiple nib contours. I'll try to add that stuff to the documentation. (It's based on a convention in the old code that was implemented but never described.)

**Comment by skef** [comment]
@jtanx Since you've done lots of graphical work and know the breadth of the elements: Are there any current widgets that display *shape*, *position* (relative to the origin) and *scale*, but not much else? Or assuming *position* is relatively easy to hack in, just *shape* and *scale*? 

I suppose the easiest solution to nib display is to keep using the dummy `charview`, but unless we can disable the palettes it needs a lot of space, and putting work and testing into disabling the palettes seems like wasted effort.

**Comment by frank-trampe** [comment]
The view that @jtanx shows is missing some of the main toolbox plus the entire layer palette, so some adjustment is surely in order. It seems to me that the easiest thing by far would be to rearrange the widgets in the stroking configuration pane more horizontally.

**Comment by skef** [comment]
> The view that @jtanx shows is missing some of the main toolbox plus the entire layer palette,

Before we save the world we should keep the current UI in mind:

olddial

In-dialog editing is difficult target and before #3865 was more or less unusuable for many years (presumably back to the hotkey config changes, and note that the Find/Replace dialog is still broken). There's basically no hope of getting the menu and parameter alt-accelerators working at the same time -- there aren't enough of them. It's one thing to worry about the usability of the lower portion and another to put effort into fixing this model.

**Comment by skef** [comment]
Oh, and if you're wondering how well undocked palletes work in combination with modality -- it's the bad version of "exactly what you would expect".

File: fontforge/python.c [hunk 11]
```diff
@@ -4367,121 +4428,216 @@ struct flaglist strokeflags[] = {
...
+                strokebkey_ellip, &type, &si->radius, &si->minorradius,
+		&si->penangle, &cap, &join, &flagtuple) ) {
+		ENDPYGETSTR();
+		PyErr_Format(PyExc_TypeError, "Wrong parameter set for "
+		                              "'elliptical' nib type" );
+		return( -1 );
+	    }
 	}
-	si->stroke_type = si_std;
-    } else if ( strcmp(str,"caligraphic")==0 || strcmp(str,"square")==0 ) {
```
Comment (dscorbett) [inline fontforge/python.c]: Is `square` no longer supported?

Comment (skef) [reply fontforge/python.c]: I don't think `square` was ever documented but since it didn't get any special handling before it's easy enough to throw another `strcmp()` to the new list.

Comment (dscorbett) [reply fontforge/python.c]: The same goes for `poly`.

**Comment by jtanx** [comment]
> @jtanx Since you've done lots of graphical work and know the breadth of the elements: Are there any current widgets that display shape, position (relative to the origin) and scale, but not much else? Or assuming position is relatively easy to hack in, just shape and scale?

None that I'm aware of, outside of that charview

File: fontforge/splinestroke.c [hunk 12]
```diff
@@ -32,3689 +32,1801 @@
...
+	                       s->from->nextcp, s->to->me, true) )
+		return Shape_BadCP;
+	    if ( !LineSameSide(s->to->me, s->to->prevcp,
+	                       s->from->nextcp, s->from->me, true) )
+		return Shape_BadCP;
+	    s->from->nextcpselected = false;
+	    s->from->selected = false;
+	    s->to->selected = true;
+	    s->to->prevcpselected = true;
+	    if ( LineSameSide(s->from->me, s->to->me, s->t
```
[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: UTMIN is the lowest possible UTanVec, so line 496 is always true for the first point.

[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: Presumably if I'm bothering to pass it back up it should have the right value, even if it's not used again. Good catch.

File: fontforge/utanvec.c [hunk 13]
```diff
@@ -0,0 +1,237 @@
...
+
+    // Check t==1
+    if ( (min_t+UTRETRY) < 1 && BPNEAR(ut, SplineUTanVecAt(spl, 1.0)) )
+        return 1.0;
+
+    // Nothing found
+    return -1;
+}
+
+void UTanVecTests() {
```
Comment (jtanx) [inline fontforge/utanvec.c]: Can we either move this into a test binary and call it as part of the tests, or just comment this out? With how fontforge is currently structured, even if this gets unused, it won't be dropped from the dll, since we export everything

Comment (skef) [reply fontforge/utanvec.c]: I don't have any strong objections to doing so, and this isn't even currently hooked up to a regression test. 

On the other hand, suppose there were a bunch of similar functions spread out through other files. What would be the concern about them? Confusion on the part of people using `nm` and the like to look at the library? (Surely not storage costs?)

Comment (jtanx) [reply fontforge/utanvec.c]: It's not a major concern tbh, but it's more of a 'repo hygine' thing, if that makes sense. I'm not worried about anyone trying to link against this, but it's kind of crap having test code exported in a releasable dll.

If I had my way and a lot more time on my hands, I'd delete all unused code and explicitly mark all exportable functions. But that's a story for another time...

**Comment by skef** [comment]
Copying from #4007, which I'm closing:

> Given the conversation so far, I'm going to declare a *preliminary* conclusion that it's OK for untraced cusps to appear in output in some cases  given that:

> 1. Overhauling the whole algorithm to produce a fundamentally different result (like that of line tracing) would be a major undertaking.
> 2. The easily available alternative is a traced cusp, which isn't obviously better. 
> 3. Setting aside what the specifications mandate, there is no clearly correct solution on *aesthetic* grounds, so these cases can be left to the user to handle with pre- or post-processing.

**Comment by skef** [comment]
There was no consensus about the replacement dialog requirements, but #4013 resolves the height problem and as far as I know leaves the new UI with more or less the same positives and negatives as the old one.

File: fontforge/python.c [hunk 14]
```diff
@@ -18811,7 +18971,7 @@ return( NULL );
     self->is_quadratic = PyInt_AsLong(PyTuple_GetItem(args,0));
     if ( PyErr_Occurred()!=NULL )
 return( NULL );
-    self->cntr_cnt = self->cntr_max = len-2;
+    self->cntr_cnt = self->cntr_max = len-1;
```
Comment (jtanx) [inline fontforge/python.c]: Was this a bug or due to a change elsewhere?

File: fontforge/python.c [hunk 15]
```diff
@@ -4367,121 +4428,218 @@ struct flaglist strokeflags[] = {
...
-    argcnt = PySequence_Size(args);
-    if ( argcnt==0 ) {
+    if ( PySequence_Size(args)==0 ) {
 	PyErr_Format(PyExc_TypeError, "Expected a name of a pen type");
-return( -1 );
+	return( -1 );
     }
+
+    InitializeStrokeInfo(si);
+    si->radius *= 2;
```
Comment (jtanx) [inline fontforge/python.c]: Why is this doubled? Because the inputs expects a diameter?

File: fontforge/python.c [hunk 16]
```diff
@@ -5268,11 +5426,11 @@ static SplineSet *_SSFromLayer(PyFF_Layer *layer, int flags) {
     return( head );
 }
 
-static SplineSet *SSFromLayer(PyFF_Layer *layer) {
+SplineSet *SSFromLayer(PyFF_Layer *layer) {
 	return _SSFromLayer(layer, pconvert_flag_none);
 }
 
-static PyFF_Layer *LayerFromSS(SplineSet *ss,PyFF_Layer *layer) {
+PyFF_Layer *LayerFromSS(SplineSet *ss,PyFF_Layer *layer) {
```
Comment (jtanx) [inline fontforge/python.c]: Why are these now non-static?

File: fontforge/splinefit.c [hunk 17]
```diff
@@ -0,0 +1,1067 @@
...
+		from->next = NULL;
+		return NULL;
+	    }
+	} else {
+	    if ( created )
+		SplinePointFree(to);
+	    return NULL;
+	}
+    } else if ( (toler_is_sumsq ? errsum : maxerr) > toler ) {
+	// XXX turn into warning
```
Comment (jtanx) [inline fontforge/splinefit.c]: Can we either do this or turn it into a TRACE?

File: fontforge/splinestroke.c [hunk 18]
```diff
@@ -3732,163 +1849,113 @@ return( first );
...
-    SplineSet *first, *last, *cur, *ret, *active = NULL, *anext;
-    SplinePoint *sp, *nsp;
-    int n, max;
-    bigreal d2, maxd2, len, maxlen;
+    SplineSet *nibs, *nib, *first, *last, *cur;
+    bigreal sn = 0.0, co = 1.0, mr;
     DBounds b;
-    BasePoint center;
     real trans[6];
+    struct simplifyinfo smpl = { sf_forcelines & sf_mergelines &
```
[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: This would certainly explain why I've been having so little luck with simplify! Oof.

File: fontforge/splinestroke.c [hunk 19]
```diff
@@ -3732,163 +1849,113 @@ return( first );
...
-	}
-	free(c.corners);
-	free(c.slopes);
-	ret = first;
-    }
-    free(c.all);
-    free(c.tpt);
-return( ret );
+	} else {
+	    c.pseudo_origin.x = b.minx+b.maxx/2;
```
[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: Yeah, that's probably wrong. And maybe untested. I'll try to do some better testing for the code that uses this.

File: fontforge/python.c (hunk 15 above)
Comment (skef) [reply fontforge/python.c]: The API has parameters for width and height (or major and minor axis). So I double here for the default values and halve down below. 

In practice I don't think this does anything because the width api doesn't have a default and the default minorradius is 0.

File: fontforge/python.c (hunk 16 above)
Comment (skef) [reply fontforge/python.c]: Hmm. I'm guessing I used these in `pythonui.c` and then that went away in a later change. I think I can reverse it.

File: fontforge/python.c (hunk 14 above)
Comment (skef) [reply fontforge/python.c]: Just a bug I ran into when testing.

**Comment by dscorbett** [comment]
The following script crashes with this branch but not with `master`.
```py3
import fontforge

font = fontforge.font()
glyph = font.createChar(0x30)
pen = glyph.glyphPen()

contour = fontforge.contour()
contour.moveTo(-43.30127018922194, 24.999999999999996)
contour.cubicTo((-57.108388934991765, 1.0853688261899606), (-48.91463117381004, -29.494151443452093), (-25.00000000000002, -43.30127018922192))
contour.cubicTo((-1.0853688261900147, -57.108388934991765), (29.494151443452086, -48.91463117381004), (43.30127018922192, -25.00000000000002))
contour.transform((1.0, 0.0, 0.0, 1.0, -129.9038105676658, 74.99999999999999))
contour.draw(pen)

contour = fontforge.contour()
contour.moveTo(-43.30127018922194, 24.999999999999996)
contour.cubicTo((-29.494151443452093, 48.91463117381004), (-1.0853688261900147, -57.108388934991765), (-25.00000000000002, -43.30127018922192))
contour.cubicTo((-48.91463117381004, -29.494151443452093), (57.108388934991765, -1.0853688261899725), (43.30127018922194, -24.999999999999996))
contour.transform((1.0, 0.0, 0.0, 1.0, -43.30126887327806, 25.000000000000004))
contour.draw(pen)

glyph.stroke('circular', 120, 'round')
glyph.removeOverlap()
```

**Comment by skef** [comment]
> The following script crashes with this branch but not with master.

```
python: ../fontforge/splinestroke.c:1493: HandleCap: Assertion `BPWITHIN(cur->last->me, p2, INTERSPLINE_MARGIN)' failed.

Program received signal SIGABRT, Aborted.
1493                assert( BPWITHIN(cur->last->me, p2, INTERSPLINE_MARGIN) );
(gdb) print p2
$1 = {x = -52.000345023148668, y = 29.934558742404136}
(gdb) print cur->last->me
$2 = {x = -52.076644987153223, y = 29.806000109456498}
```

`INTERSPLINE_MARGIN` is 0.1, so what's going on here is an assertion that isn't quite tuned right. I'll adjust this but this isn't something someone would hit in the production version.

File: fontforge/splinestroke.c (hunk 19 above)
[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: I'll fix this line but the code that uses it still needs work, so let's leave this unresolved.

**Comment by jtanx** [comment]
This is currently tripping asan if you do something like:

1. Draw any shape
2. Explicitly select a control point either via clicking or Ctrl+A
3. Run expand stroke (default settings are fine)

```
=================================================================
==2343==ERROR: AddressSanitizer: heap-use-after-free on address 0x60800000f5a0 at pc 0x0000006539d3 bp 0x7ffce6ce9850 sp 0x7ffce6ce9848
READ of size 8 at 0x60800000f5a0 thread T0
    #0 0x6539d2 in CVInfoDrawText /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:4109:17
    #1 0x64e76c in CVInfoDraw /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:4187:5
    #2 0x6f51d4 in CVCrossing /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:4198:5
    #3 0x6edce0 in v_e_h /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:5735:2
    #4 0xf04f47 in GiveToAll /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:592:6
    #5 0xf04e35 in GiveToAll /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:588:6
    #6 0xf00c0a in _GWidget_TopLevel_eh /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:679:2
    #7 0xf6335c in _GGDKDraw_CallEHChecked /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:334:9
    #8 0xf4f4c4 in _GGDKDraw_DispatchEvent /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:1237:9
    #9 0x7f2c1fb85764  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x37764)
    #10 0x7f2c1fbb5f91  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x67f91)
    #11 0x7f2c1ea8b416 in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c416)
    #12 0x7f2c1ea8b64f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c64f)
    #13 0x7f2c1ea8b6db in g_main_context_iteration (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c6db)
    #14 0xf5bc09 in GGDKDrawProcessPendingEvents /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:2176:16
    #15 0xf11b1e in GDrawProcessPendingEvents /home/jeremy/ffstaging/build/../gdraw/gdraw.c:779:5
    #16 0x8ba9da in MakeStrokeDlg /home/jeremy/ffstaging/build/../fontforgeexe/cvstroke.c:1212:9
    #17 0x8aa448 in CVStroke /home/jeremy/ffstaging/build/../fontforgeexe/cvstroke.c:1233:5
    #18 0x6ca499 in CVMenuStroke /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:9771:5
    #19 0xfcb682 in GMenuBarCheckHotkey /home/jeremy/ffstaging/build/../gdraw/gmenu.c:1966:7
    #20 0xfca825 in GMenuBarCheckKey /home/jeremy/ffstaging/build/../gdraw/gmenu.c:2015:9
    #21 0xf034d4 in _GWidget_TopLevel_Key /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:507:23
    #22 0xf00d0d in _GWidget_TopLevel_eh /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:682:9
    #23 0xf6335c in _GGDKDraw_CallEHChecked /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:334:9
    #24 0xf4f4c4 in _GGDKDraw_DispatchEvent /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:1237:9
    #25 0x7f2c1fb85764  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x37764)
    #26 0x7f2c1fbb5f91  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x67f91)
    #27 0x7f2c1ea8b416 in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c416)
    #28 0x7f2c1ea8b64f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c64f)
    #29 0x7f2c1ea8b6db in g_main_context_iteration (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c6db)
    #30 0xf5be36 in GGDKDrawEventLoop /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:2204:17
    #31 0xf11c5e in GDrawEventLoop /home/jeremy/ffstaging/build/../gdraw/gdraw.c:789:5
    #32 0xe2a647 in fontforge_main /home/jeremy/ffstaging/build/../fontforgeexe/startui.c:1415:5
    #33 0x53eba1 in main /home/jeremy/ffstaging/build/../fontforgeexe/main.c:33:12
    #34 0x7f2c1e66fb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #35 0x433329 in _start (/home/jeremy/ffstaging/build/bin/fontforge+0x433329)

0x60800000f5a0 is located 0 bytes inside of 96-byte region [0x60800000f5a0,0x60800000f600)
freed by thread T0 here:
    #0 0x4fd278 in __interceptor_free (/home/jeremy/ffstaging/build/bin/fontforge+0x4fd278)
    #1 0x7f2c21f26859 in SplinePointMDFree /home/jeremy/ffstaging/build/../fontforge/splineutil.c:212:5
    #2 0x7f2c21f26f9b in SplinePointListMDFree /home/jeremy/ffstaging/build/../fontforge/splineutil.c:265:6
    #3 0x8bbb2c in CVStrokeIt /home/jeremy/ffstaging/build/../fontforgeexe/cvstroke.c:131:3
    #4 0x8d6b96 in _Stroke_OK /home/jeremy/ffstaging/build/../fontforgeexe/cvstroke.c:263:2
    #5 0x8d8f03 in Stroke_OK /home/jeremy/ffstaging/build/../fontforgeexe/cvstroke.c:273:9
    #6 0xedc6d3 in GButtonInvoked /home/jeremy/ffstaging/build/../gdraw/gbuttons.c:257:2
    #7 0xed2bad in gbutton_mouse /home/jeremy/ffstaging/build/../gdraw/gbuttons.c:485:3
    #8 0xefce03 in _GWidget_Container_eh /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:304:16
    #9 0xf02696 in _GWidget_TopLevel_eh /home/jeremy/ffstaging/build/../gdraw/gcontainer.c:747:11
    #10 0xf6335c in _GGDKDraw_CallEHChecked /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:334:9
    #11 0xf4f4c4 in _GGDKDraw_DispatchEvent /home/jeremy/ffstaging/build/../gdraw/ggdkdraw.c:1237:9
    #12 0x7f2c1fb85764  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x37764)

previously allocated by thread T0 here:
    #0 0x4fd88f in calloc (/home/jeremy/ffstaging/build/bin/fontforge+0x4fd88f)
    #1 0x7f2c21cdc1cc in SFDGetSplineSet /home/jeremy/ffstaging/build/../fontforge/sfd.c:4126:8
    #2 0x7f2c21d0ae99 in SFDGetChar /home/jeremy/ffstaging/build/../fontforge/sfd.c:5698:42
    #3 0x7f2c21d2f325 in SFD_GetFont /home/jeremy/ffstaging/build/../fontforge/sfd.c:8984:10
    #4 0x7f2c21d01af9 in SFD_Read /home/jeremy/ffstaging/build/../fontforge/sfd.c:9077:7
    #5 0x7f2c21d0218e in _SFDRead /home/jeremy/ffstaging/build/../fontforge/sfd.c:9110:9
    #6 0x7f2c21de38ac in _ReadSplineFont /home/jeremy/ffstaging/build/../fontforge/splinefont.c:1179:11
    #7 0x7f2c21de5e71 in ReadSplineFont /home/jeremy/ffstaging/build/../fontforge/splinefont.c:1322:9
    #8 0x7f2c21de63c6 in LoadSplineFont /home/jeremy/ffstaging/build/../fontforge/splinefont.c:1380:7
    #9 0x7f2c217bb8ca in ViewPostScriptFont /home/jeremy/ffstaging/build/../fontforge/fontviewbase.c:1347:22
    #10 0xe2a584 in fontforge_main /home/jeremy/ffstaging/build/../fontforgeexe/startui.c:1391:18
    #11 0x53eba1 in main /home/jeremy/ffstaging/build/../fontforgeexe/main.c:33:12
    #12 0x7f2c1e66fb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: heap-use-after-free /home/jeremy/ffstaging/build/../fontforgeexe/charview.c:4109:17 in CVInfoDrawText
Shadow bytes around the buggy address:
  0x0c107fff9e60: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9e70: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9e80: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9e90: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9ea0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c107fff9eb0: fa fa fa fa[fd]fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9ec0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9ed0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9ee0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9ef0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff9f00: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2343==ABORTING
```

**Comment by dscorbett** [comment]
I did not build with `-DCMAKE_BUILD_TYPE=Debug`, so the `INTERSPLINE_MARGIN` assertion failure was a different issue. My script is still crashing with the latest version of this branch. Here is the stack trace.
```
0   libsystem_kernel.dylib        	0x00007fff7c86c2c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7c927bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff7c7d66a6 abort + 127
3   libsystem_malloc.dylib        	0x00007fff7c8e5077 malloc_vreport + 545
4   libsystem_malloc.dylib        	0x00007fff7c8e4e38 malloc_report + 151
5   libfontforge.4.dylib          	0x000000010a788eef SplineSetRemoveOverlap + 9935
6   libfontforge.4.dylib          	0x000000010a7b4b58 SplineSetStroke + 8008
7   libfontforge.4.dylib          	0x000000010a6db622 PyFFGlyph_Stroke + 82
8   org.python.python             	0x000000010b225499 _PyMethodDef_RawFastCallKeywords + 537
9   org.python.python             	0x000000010b229c99 _PyMethodDescr_FastCallKeywords + 81
10  org.python.python             	0x000000010b2b9436 call_function + 782
11  org.python.python             	0x000000010b2b235e _PyEval_EvalFrameDefault + 6742
12  org.python.python             	0x000000010b2b9bfd _PyEval_EvalCodeWithName + 1698
13  org.python.python             	0x000000010b2b0865 PyEval_EvalCode + 51
14  org.python.python             	0x000000010b2dec74 run_mod + 54
15  org.python.python             	0x000000010b2ddca7 PyRun_FileExFlags + 160
16  org.python.python             	0x000000010b2dd35e PyRun_SimpleFileExFlags + 270
17  org.python.python             	0x000000010b2f5b6e pymain_main + 5445
18  org.python.python             	0x000000010b2f4623 Py_Main + 52
19  libfontforge.4.dylib          	0x000000010a6cd775 PyFF_Main + 133
20  libfontforge.4.dylib          	0x000000010a6fa792 CheckIsScript + 818
21  fontforge                     	0x000000010a338cdd fontforge_main + 1005
22  libdyld.dylib                 	0x00007fff7c7313d5 start + 1
```

**Comment by skef** [comment]
@dscorbett: Ah, OK.

I split your script into two:

```
#!/usr/bin/env python

import fontforge
import pickle

font = fontforge.font()
glyph = font.createChar(0x30)
pen = glyph.glyphPen()

contour = fontforge.contour()
contour.moveTo(-43.30127018922194, 24.999999999999996)
contour.cubicTo((-57.108388934991765, 1.0853688261899606), (-48.91463117381004, -29.494151443452093), (-25.00000000000002, -43.30127018922192))
contour.cubicTo((-1.0853688261900147, -57.108388934991765), (29.494151443452086, -48.91463117381004), (43.30127018922192, -25.00000000000002))
contour.transform((1.0, 0.0, 0.0, 1.0, -129.9038105676658, 74.99999999999999))
contour.draw(pen)

contour = fontforge.contour()
contour.moveTo(-43.30127018922194, 24.999999999999996)
contour.cubicTo((-29.494151443452093, 48.91463117381004), (-1.0853688261900147, -57.108388934991765), (-25.00000000000002, -43.30127018922192))
contour.cubicTo((-48.91463117381004, -29.494151443452093), (57.108388934991765, -1.0853688261899725), (43.30127018922194, -24.999999999999996))
contour.transform((1.0, 0.0, 0.0, 1.0, -43.30126887327806, 25.000000000000004))
contour.draw(pen)

l = glyph.foreground
l.stroke('circular', 120, 'round', removeoverlap='none', simplify=False, extrema=False)
fl = open('problem_layer.P', 'wb')
pickle.dump(l, fl)
fl.close()
```

```
#!/usr/bin/env python

import fontforge
import pickle

fl = open('problem_layer.P', 'rb')
l = pickle.load(fl)
fl.close()

l.removeOverlap()

```
Those keyword parameter additions in the first have the effect of outputting the geometry that would have been passed to the "internal" `removeOverlap()` pass. Then it pickles the layer into file `problem_layer.P`. The second script loads the layer from that file and runs `removeOverlap()` on it.

Could you try these on your configuration and verify that the first script succeeds and the second script crashes? And if it does could you make a zip with the two scripts and `problem_layer.P` and file a new  issue "against" the Remove Overlap facility? That way it will be clear where the output came from but the testing and fix won't need to be tied to the `stroke` branch.

File: fontforge/python.c (hunk 14 above)
Comment (skef) [reply fontforge/python.c]: I remember this now. There's a zip file above with some python code to store and retrieve custom convex nibs for the UI, using the python interface I added for that purpose. It stores its data by pickling a dictionary that contains `fontforge.layer`s. That's how I found and fixed this bug -- the pickling didn't work without the change.

**Comment by skef** [comment]
@dscorbett on second thought the pickling might not work on the current `master`. (Search for 'pickle" above for my new comment about that.) Give it a shot, though.

**Comment by skef** [comment]
@dscorbett: Ideally independent testing should match what github is doing with this PR, which amounts to rebasing the commits to this thread off the current master. I don't know if you're doing that, but I just tried it (the rebase is "clean") and confirmed I still see the crash. If the eventual fix goes directly into the master as with #3998 it will have to be confirmed that way.

**Comment by jtanx** [comment]
Yeah this branch being behind master is a bit annoying. That's why I like rebasing ;) Granted I don't know what that'd do with the references to the PRs made to this branch.


It might be about time to merge this to master anyway. I'll take a final look a bit later, but I've reviewed most of it and I don't see any major glaring issues, and we can always file issues/prs against master if needed. Same strategy as the cmake changes...

**Comment by skef** [comment]
@jtanx: @frank-trampe has indicated that he wants some back-and-forth with the user base on the email lists before merging/committing. So it could be a little while yet.

I think we can manage things as we have been for a bit longer. I'll try to any systemic testing on my part using a rebased version.

**Comment by skef** [comment]
Given the fontforge-users announcement, I'm going to rebase the `stroke` branch.

**Comment by skef** [comment]
@jtanx I guess the infrastructure is more clever than I thought it would be. The PR annotations seem to have survived the rebasing. Nice!

**Comment by frank-trampe** [comment]
Well that's handy. In the past, I've tended to squash into a separate branch and thus a separate pull request to be safe, which is admittedly a little clunky. I'm happy to see that that is now unnecessary.

**Comment by skef** [comment]
A couple problems I'm aware of that are next on my list to fix:

1. The `NibIsValid()` control point tolerances are too tight relative to rounding. I think the proper solution is to replicate the smooth point criteria from `SplinePointCategory()`
2. Some of the joint types (particularly MiterLimit) don't work properly with a custom nib offset from the origin. The problematic code makes use of the `pseudo_origin`. As a workaround you can set `sip->leave_users_center` to true in `splinestroke.c:InitializeStrokeInfo()`.

**Comment by dscorbett** [comment]
The following script seems to run forever on this branch, whereas it terminates promptly on `master`.
```py3
import fontforge

font = fontforge.font()
glyph = font.createChar(0x30)
pen = glyph.glyphPen()

pen.moveTo(-86.60254037844386, -50.000000000000014)
pen.curveTo((-68.73926088303567, -80.94010767585033), (-35.726558990816386, -99.99999999999999), (-1.8369701987210297e-14, -100.0))
pen.curveTo((35.72655899081635, -99.99999999999999), (68.73926088303563, -80.94010767585034), (86.60254037844383, -50.00000000000004))
pen.endPath()
glyph.transform((1.4999999999999996, -0.8660254037844384, -0.8660254037844384, 2.500000000000001, 0.0, 0.0))
glyph.stroke('circular', 70, 'round')
```

**Comment by frank-trampe** [comment]
@dscorbett, could you attach gdb, `break` where execution stalls, and determine out where it's stuck (via `where`)?

**Comment by skef** [comment]
@dscorbett: I can reproduce, and it appears to get stuck in the extrema code. When I change the last line to:

```
glyph.stroke('circular', 70, 'round', extrema=False)

```
the script completes. 

A typical backtrace without that change is:
```
(gdb) where
#0  0x00007ffff6cf04e8 in RealNear (a=132.56927351912492, b=132.65762762111765) at ../fontforge/splineutil2.c:171
#1  0x00007ffff6cf0cc6 in SplineIsLinear (spline=0x5555556bc390) at ../fontforge/splineutil2.c:277
#2  0x00007ffff6c9b5d3 in SplineRefigure3 (spline=0x5555556bc390) at ../fontforge/splinerefigure.c:102
#3  0x00007ffff6c83b1c in SplineRefigure (spline=0x5555556bc390) at ../fontforge/splineorder2.c:1347
#4  0x00007ffff6cfc329 in ForceEndPointExtrema (s=0x5555556bc390, isto=1) at ../fontforge/splineutil2.c:2564
#5  0x00007ffff6cfdae5 in SplineAddExtrema (s=0x5555556bc390, always=1, lenbound=0, offsetbound=0, b=0x7fffffffdcb0) at ../fontforge/splineutil2.c:2781
#6  0x00007ffff6cfe071 in SplineSetAddExtrema (sc=0x0, ss=0x5555556bc2e0, between_selected=ae_all, emsize=1000) at ../fontforge/splineutil2.c:2873
#7  0x00007ffff6cfe1b0 in SplineCharAddExtrema (sc=0x0, head=0x5555556b9c30, between_selected=ae_all, emsize=1000) at ../fontforge/splineutil2.c:2899
#8  0x00007ffff6cc8aa7 in SplineSetStroke (ss=0x5555556b7180, si=0x7fffffffdee0, order2=0) at ../fontforge/splinestroke.c:1951
#9  0x00007ffff6ba509c in PyFFGlyph_Stroke (self=0x7ffff7175f48, args=0x7ffff71c8ca8, keywds=0x0) at ../fontforge/python.c:9302
#10 0x00007ffff7b84290 in _PyMethodDef_RawFastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#11 0x00007ffff7bbcb7f in _PyMethodDescr_FastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#12 0x00007ffff7bbcd14 in  () at /usr/lib/libpython3.7m.so.1.0
#13 0x00007ffff7bf9f90 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.7m.so.1.0
#14 0x00007ffff7ba8d18 in _PyEval_EvalCodeWithName () at /usr/lib/libpython3.7m.so.1.0
#15 0x00007ffff7ba9aca in PyEval_EvalCodeEx () at /usr/lib/libpython3.7m.so.1.0
#16 0x00007ffff7ba9aec in PyEval_EvalCode () at /usr/lib/libpython3.7m.so.1.0
#17 0x00007ffff7c7a8a5 in  () at /usr/lib/libpython3.7m.so.1.0
#18 0x00007ffff7c7ac2b in PyRun_FileExFlags () at /usr/lib/libpython3.7m.so.1.0
#19 0x00007ffff7c80ec7 in PyRun_SimpleFileExFlags () at /usr/lib/libpython3.7m.so.1.0
#20 0x00007ffff7c83022 in  () at /usr/lib/libpython3.7m.so.1.0
#21 0x00007ffff7c831cc in _Py_UnixMain () at /usr/lib/libpython3.7m.so.1.0
#22 0x00007ffff7decee3 in __libc_start_main () at /usr/lib/libc.so.6
#23 0x000055555555505e in _start ()

```

**Comment by skef** [comment]
I don't know exactly what "the deal" is yet, but what happens in `SplineAddExtrema()` is that the preparation and checks eventually get down to `ForceEndPointExtrema(s, 1);` on line 2781, which returns 1. That causes `restart` to be true and the outer `for` loop cycles around again. I suspect the problem is that the loop is supposed to terminate on an iteration that does no work, and `ForceEndPointExtrema()` is claiming to do work every time through. 

`ForceEndPointExtrema()` is suspicious. For one thing the comment says:
> if the control point is very close to the base point then remove it
And the code does this in the sense of setting `noprevcp` to true. But while a cubic spline can have a control point colocated with its on-curve point, one shouldn't have only a single control point (right?). 

This patch resolves the "no work done" problem for this case, but I'm not confident about it as a general fix:
```
diff --git a/fontforge/splineutil2.c b/fontforge/splineutil2.c
index 348f26e70..c3a0f8404 100644
--- a/fontforge/splineutil2.c
+++ b/fontforge/splineutil2.c
@@ -2553,6 +2553,8 @@ static int ForceEndPointExtrema(Spline *s,int isto) {
 return( -1 );
     len = sqrt(len);
     if ( mylen<30*len && mylen<cplen && mylen<1 ) {
+       if ( mylen==0 )
+           return -1;
        if ( isto ) {
            s->to->noprevcp = true;
            s->to->prevcp = s->to->me;
```

File: fontforge/splinestroke.c (hunk 19 above)
[the remark this answers is not in the document]
Comment (skef) [reply fontforge/splinestroke.c]: I did some further testing on the code that makes use of pseudo-origin (which has to do with join and cap geometry), and it now seems to work as expected (fingers crossed).

File: fontforge/python.c (hunk 14 above)
Comment (skef) [reply fontforge/python.c]: This went in as a separate fix to aid in testing.

File: fontforge/ffpython.h [hunk 20]
```diff
@@ -138,7 +139,7 @@ typedef struct ff_contour {
     int spiro_cnt;
     char *name;
 } PyFF_Contour;
-static PyTypeObject PyFF_ContourType;
+extern PyTypeObject PyFF_ContourType;
```
Comment (jtanx) [inline fontforge/ffpython.h]: static->extern? Same for PyFF_LayerType

Comment (skef) [reply fontforge/ffpython.h]: Wasn't that a static declaration in a header file? Doesn't that lead to one object of that type per object file that includes it?

Offhand I'm not certain about this so much as generally wary of seeing "static" in header files except for very unusual circumstances.

Comment (jtanx) [reply fontforge/ffpython.h]: Yeah if it was truly static it should probably just be moved into python.c.

**Comment by skef** [comment]
@jtanx Thank you very much for all this review work and the bug fixes and improvements that resulted. 

Things are also ready from my perspective. The only improvement currently planned is implementing arcs joins, and that can go in separately whenever it gets done. 

On the other hand I suppose there's no hurry. There hasn't been any further discussion on the users list but perhaps there were some direct responses. We can sort things out between here and #3933.

**Comment by frank-trampe** [comment]
I have not received any direct communications as a result of the mailing list post, and we actually have a reasonable number of commits in this branch. I think that we all agree that merge time has come, but I'll leave that to you.

**Comment by skef** [comment]
Let's merge then! I'll do it squashed but we can leave the branch around for a bit in case it's needed to help rework things.

**Comment by ctrlcctrlv** [comment]
Wow, awesome work everyone! :tada:

**Comment by NiLuJe** [comment]
FYI, this broke the build with `ENABLE_TILE_PATH`:

```
/var/tmp/portage/media-gfx/fontforge-20191211/work/fontforge/fontforgeexe/tilepath.c: In function ‘AdjustPoint’:                                                                                                                                                                                                                                                          
/var/tmp/portage/media-gfx/fontforge-20191211/work/fontforge/fontforgeexe/tilepath.c:574:19: error: ‘FitPoint’ {aka ‘struct fitpoint’} has no member named ‘y’                                                                                                                                                                                                            
  574 |   to->p.x = x1; to->y = y1;                                                                                                                                                                                                                                                                                                                                       
      |                   ^~                                                                                                                                                                                                                                                                                                                                              
/var/tmp/portage/media-gfx/fontforge-20191211/work/fontforge/fontforgeexe/tilepath.c: In function ‘TDMakePoint’:                                                                                                                                                                                                                                                          
/var/tmp/portage/media-gfx/fontforge-20191211/work/fontforge/fontforgeexe/tilepath.c:613:17: error: ‘tp’ undeclared (first use in this function); did you mean ‘fp’?                                                                                                                                                                                                      
  613 |     new->me.x = tp.p.x; new->me.y = tp.p.y;                                                                                                                                                                                                                                                                                                                       
      |                 ^~                                                                                                                                                                                                                                                                                                                                                
      |                 fp                                                                                                                                                                                                                                                                                                                                                
/var/tmp/portage/media-gfx/fontforge-20191211/work/fontforge/fontforgeexe/tilepath.c:613:17: note: each undeclared identifier is reported only once for each function it appears in
```

A quick'n dirty naive patching appears to clobber things into order:

```diff
diff --git a/fontforgeexe/tilepath.c b/fontforgeexe/tilepath.c
index b329b5409..2575058eb 100644
--- a/fontforgeexe/tilepath.c
+++ b/fontforgeexe/tilepath.c
@@ -571,7 +571,7 @@ static void AdjustPoint(TD *td,Spline *spline,bigreal t, FitPoint *to) {
        } else {
            bigreal s=(dy1*dx2/dy2-dx1);
            if ( s>-.00001 && s<.00001 ) {      /* essentially parallel */
-               to->p.x = x1; to->y = y1;
+               to->p.x = x1; to->p.y = y1;
            } else {
                bigreal t1 = (x1-x2- dx2/dy2*(y1-y2))/s;
                to->p.x = x1 + dx1*t1;
@@ -610,7 +610,7 @@ static SplinePoint *TDMakePoint(TD *td,Spline *old,real t) {
 
     AdjustPoint(td,old,t,&fp);
     new = chunkalloc(sizeof(SplinePoint));
-    new->me.x = tp.p.x; new->me.y = tp.p.y;
+    new->me.x = fp.p.x; new->me.y = fp.p.y;
     new->nextcp = new->me;
     new->prevcp = new->me;
     new->nonextcp = new->noprevcp = true;
```
