### PR TITLE
ustring.c: u2utf8_copyn: truncate at the first invalid utf8 char instead of returning null

### LINKED ISSUE #4294: Crash when getting surrogate glyph info
Opening the “Glyph Info” window for a surrogate crashes FontForge. I am using version 20200314 on macOS 10.14.6. To reproduce:

* Select a surrogate in the main grid, e.g. U+D800.
* Open the “Element” menu.
* Click “Glyph Info...”.

[Here is the crash report.](https://github.com/fontforge/fontforge/files/4529202/fontforge_2020-04-24-094345.txt)

### PR DESCRIPTION
**Pull request by jtanx**
Fixes #4294. e.g. from that case, a single surrogate is not valid utf-8

### Type of change

- **Bug fix**

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Did I cause this regression? Change looks fine to me.

File: Unicode/ustring.c [hunk 1]
```diff
@@ -655,18 +655,19 @@ char *u2utf8_copy(const unichar_t *ubuf) {
...
-	return( utf8buf );
-    }
-    free( utf8buf );
-    return( NULL );
+    while ( (pt2=utf8_idpb(pt,*ubuf++,0)) && --len )
+	pt = pt2;
+
+    if ( pt2 )
+	pt = pt2;
+
```
Comment (ctrlcctrlv) [inline Unicode/ustring.c:668]: Now that I'm on my PC I can confirm that I did not cause this. I thought I may have in #4160, but that didn't touch this function.

I think a developer `TRACE` warning should be added here on truncation. It seems like the kind of thing to make debugging difficult when we're expecting a string of one length and getting a length of another. We may even want to consider changing the function signature to int *len so lengths can be verified as needed.

File: inc/basics.h [hunk 2]
```diff
@@ -67,9 +67,9 @@ typedef uint32 unichar_t;
 /* A macro to print a string for debug purposes
  */
 #ifndef NDEBUG
-#define TRACE(...) printf(__VA_ARGS__)
+#define TRACE(...) fprintf(stderr, __VA_ARGS__)
 #else
-#define TRACE(...)
+#define TRACE(...) while(0)
```
Comment (ctrlcctrlv) [inline inc/basics.h:72]: I don't understand how this even compiles (I assumed you'd want `do {} while (0)`), but it does, so this looks fine to me now :-)

Comment (skef) [reply inc/basics.h:72]:
```
TRACE("u2utf8_copyn: truncated on invalid char 0x%x\n", ubuf[-1]);
```
(for example) is replaced by:
```
while(0);
```
which one could read as:
```
while (false)
    ;
```

Comment (ctrlcctrlv) [reply inc/basics.h:72]: Oh, I see, okay, the semicolon makes it work. I thought a statement was needed, but I just tested it, and `if(true);` also is a no-op. Neat!

Comment (skef) [reply inc/basics.h:72]: Various different conventions turn up for this but they're often partly intended to "eat" the trailing semicolon on the TRACE or ASSERT or whatever, either because leaving it would be syntactically illegal or (more commonly) to avoid lint or compiler warnings.
