### PR TITLE
Fix for #3229 NULL pointer dereference in readcffglyphs

### LINKED ISSUE #3229: NULL pointer dereference in readcffglyphs
Hello.

I found a NULL pointer dereference in fontforge.

Please confirm.

Thanks.

PoC Download:  [Null_readcffglyphs.zip](https://github.com/fontforge/fontforge/files/1574599/Null_readcffglyphs.zip)

Steps to reproduce:
1.Download the .POC files.
2.Compile the source code with ASan.
3.Execute the following command
   : ./fontforge -lang=ff -c 'Open($1)' $FILE

```
=================================================================
==12820==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ffff5a0c9a3 bp 0x7fffffff75d0 sp 0x7fffffff7120 T0)
==12820==The signal is caused by a READ memory access.
==12820==Hint: address points to the zero page.
    #0 0x7ffff5a0c9a2 in readcffglyphs /home/karas/fontforge/fontforge/parsettf.c:3979:13
    #1 0x7ffff59f77fa in readttf /home/karas/fontforge/fontforge/parsettf.c:5560:8
    #2 0x7ffff59ef043 in _SFReadTTF /home/karas/fontforge/fontforge/parsettf.c:6299:11
    #3 0x7ffff5cfb254 in _ReadSplineFont /home/karas/fontforge/fontforge/splinefont.c:1115:11
    #4 0x7ffff5cfd93d in ReadSplineFont /home/karas/fontforge/fontforge/splinefont.c:1286:9
    #5 0x7ffff5cfd93d in LoadSplineFont /home/karas/fontforge/fontforge/splinefont.c:1344
    #6 0x7ffff5b57eb0 in bOpen /home/karas/fontforge/fontforge/scripting.c:1858:10
    #7 0x7ffff5bc39cd in docall /home/karas/fontforge/fontforge/scripting.c:9596:6
    #8 0x7ffff5bbbb11 in handlename /home/karas/fontforge/fontforge/scripting.c:9707:2
    #9 0x7ffff5bbbb11 in term /home/karas/fontforge/fontforge/scripting.c:9951
    #10 0x7ffff5bbae03 in mul /home/karas/fontforge/fontforge/scripting.c:10096:5
    #11 0x7ffff5bb9814 in add /home/karas/fontforge/fontforge/scripting.c:10141:5
    #12 0x7ffff5bb8bc1 in comp /home/karas/fontforge/fontforge/scripting.c:10216:5
    #13 0x7ffff5bb7ec9 in _and /home/karas/fontforge/fontforge/scripting.c:10259:5
    #14 0x7ffff5bb60f8 in _or /home/karas/fontforge/fontforge/scripting.c:10290:5
    #15 0x7ffff5bb60f8 in assign /home/karas/fontforge/fontforge/scripting.c:10322
    #16 0x7ffff5b44ea9 in expr /home/karas/fontforge/fontforge/scripting.c:10400:5
    #17 0x7ffff5b44ea9 in ff_statement /home/karas/fontforge/fontforge/scripting.c:10609
    #18 0x7ffff5b483aa in ProcessNativeScript /home/karas/fontforge/fontforge/scripting.c:10757:4
    #19 0x7ffff5b49d8a in _CheckIsScript /home/karas/fontforge/fontforge/scripting.c
    #20 0x7ffff5b49d8a in CheckIsScript /home/karas/fontforge/fontforge/scripting.c:10886
    #21 0x7ffff78603de in fontforge_main /home/karas/fontforge/fontforgeexe/startui.c:1058:5
    #22 0x7ffff3a3c3f0 in __libc_start_main /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:291
    #23 0x419d79 in _start (/home/karas/fontforge/fontforgeexe/.libs/fontforge+0x419d79)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/karas/fontforge/fontforge/parsettf.c:3979:13 in readcffglyphs
==12820==ABORTING
```

==========================================
[Acknowledgement]
This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001, Innovation hub for high Performance Computing]

### PR DESCRIPTION
**Pull request by skef**
The font provided in the bug is corrupt; `ttfdump` prints "Unexpected EOF". 

This change protects against dereferencing a NULL `subtables` pointer. It then determines that there are no glyphs found and returns 0 from `readcffglyphs`, ending the attempt to open the file.

Closes #3229 

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

File: fontforge/parsettf.c [hunk 1]
```diff
@@ -3974,18 +3974,20 @@ return( 0 );
...
-	fseek(ttf,info->cff_start+dicts[which]->fdselectoff,SEEK_SET);
-	fdselect = readfdselect(ttf,dicts[which]->glyphs.cnt,info);
-	for ( j=0; subdicts[j]!=NULL; ++j ) {
-	    if ( subdicts[j]->private_offset!=-1 )
-		readcffprivate(ttf,subdicts[j],info);
-	    if ( subdicts[j]->charsetoff!=-1 )
-		readcffset(ttf,subdicts[j],info);
+	if ( subdicts!=NULL ) {
+	    fseek(ttf,info->cff_start+dicts[which]->fdselectoff,SEEK_SET);
+	    fdselect = readfdselect(ttf,dicts[which]->glyphs.cnt,info);
```
Comment (frank-trampe) [inline fontforge/parsettf.c]: Are you sure that the statements affecting the read position go inside the conditional?

Comment (skef) [reply fontforge/parsettf.c]: Good question. Of the various `read` functions only one has a `SEEK_CUR` and its in the middle. The general strategy is to start fresh with a `SEEK_SET` or, occasionally, a `SEEK_LAST`. That includes `readcffenc` called below in this function. 

Looking at the question from the other direction, it doesn't seem like past the end of the last subdict for `which`, even given that `which` is (probably?) almost always going to be zero, is enough of a particular place for the code to rely on.
