### PR TITLE
Fix woff2 decoding

### LINKED ISSUE #5101: Unable to open FontAwesome 6.2.0 WOFF2
FontForge 228685, both Windows 10 and Linux (ArchLinux)

FontForge gives "[file] is not in a known format (or uses features of that format fontforge does not support, or is so badly corrupted as to be unreadable)".

Opening older versions of FontAwesome (5.15.4 for example) work as expected, so does opening the files in question with basically any other font tool including `woff2_decompress`.

https://fontawesome.com/v6/download
https://fontawesome.com/v5/download

```
$ woff2_info brands-v5.15.4.woff2 
Processing brands-v5.15.4.woff2 => brands-v5.15.4.woff2
WOFF2Header
signature           0x774f4632
flavor              0x00010000
length              76736
numTables           13
reserved            0
totalSfntSize       133984
totalCompressedSize 76646
majorVersion        331
minorVersion        34340
metaOffset          0
metaLength          0
metaOrigLength      0
privOffset          0
privLength          0
TableDirectory starts at +48
Entry offset flags tag  origLength txLength
    0     48  0x3f FFTM         28
    1     54  0x1a GDEF         30
    2     56  0x06 OS/2         96
    3     58  0x00 cmap       1530
    4     61  0x11 gasp          8
    5     63  0x0a glyf     122300    95906
    6     70  0x01 head         54
    7     72  0x02 hhea         36
    8     74  0x03 hmtx       1836
    9     77  0x0b loca        920        0
   10     81  0x04 maxp         32
   11     83  0x05 name       1413
   12     86  0x07 post       5469
TableDirectory ends at +89
```

```
$ woff2_info brands-v6.2.0.woff2 
Processing brands-v6.2.0.woff2 => brands-v6.2.0.woff2
WOFF2Header
signature           0x774f4632
flavor              0x00010000
length              107460
numTables           10
reserved            0
totalSfntSize       180184
totalCompressedSize 107386
majorVersion        770
minorVersion        256
metaOffset          0
metaLength          0
metaOrigLength      0
privOffset          0
privLength          0
TableDirectory starts at +48
Entry offset flags tag  origLength txLength
    0     48  0x01 head         56
    1     50  0x02 hhea         36
    2     52  0x04 maxp         32
    3     54  0x06 OS/2         96
    4     56  0x03 hmtx       2052
    5     59  0x00 cmap       4664
    6     62  0xca glyf     170104
    7     66  0xcb loca       2056
    8     69  0x05 name       1056
    9     72  0x07 post         32
TableDirectory ends at +74
```

### PR DESCRIPTION
**Pull request by jtanx**
Fixes #5101

Re-reading the WOFF2 spec:

> The "totalSfntSize" value in the WOFF2 Header is intended to be
> used for reference purposes only. It may represent the size of
> the uncompressed input font file, but if the transformed 'glyf'
> and 'loca' tables are present, the uncompressed size of the
> reconstructed tables and the total decompressed font size may
> differ substantially from the original total size specified in
> the WOFF2 Header.

### Type of change

- **Bug fix**

### CODE REVIEW

**Review by skef — APPROVED** [review]
lgtm

File: fontforge/woff2.cc [hunk 1]
```diff
@@ -26,39 +26,33 @@
...
     }
 }
 
-int woff2_convert_woff2_to_ttf(const uint8_t *data, size_t length, uint8_t *result, size_t *result_length)
+int woff2_convert_woff2_to_ttf(const uint8_t *data, size_t length, uint8_t **result, size_t *result_length)
 {
     try {
-        woff2::WOFF2MemoryOut output(result, *result_length);
+        std::string buffer(std::min(woff2::ComputeWOFF2FinalSize(data, length), woff2::kDefaultMaxSize), 0);
+        woff2::WOFF2StringOut output(&buffer);
```
Comment (yisibl) [inline fontforge/woff2.cc:48]: Hi @jtanx 

Does changing from `WOFF2MemoryOut` to `WOFF2StringOut` have any impact on performance?

Comment (jtanx) [reply fontforge/woff2.cc:48]: None that I'd care about, why?
