### PR TITLE
Don't crash if encoding is negative

### LINKED ISSUE #4427: `Some Time Later.sfd` causes a crash on latest release and master, but not under 20190801
https://github.com/ctrlcctrlv/some-time-later/blob/master/Some%20Time%20Later.sfd

This font was developed under FontForge, so it's not some strange SFD.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ad7d84 in SFDSetEncMap (sf=0x555555d318e0, orig_pos=1178, 
--Type <RET> for more, q to quit, c to continue without paging--
     at ../fontforge/sfd.c:4847
4847		map->map[enc] = orig_pos;
(gdb) bt
#0  0x00007ffff7ad7d84 in SFDSetEncMap (sf=0x555555d318e0, orig_pos=1178, enc=-8796) at ../fontforge/sfd.c:4847
#1  0x00007ffff7ada3c1 in SFDGetChar (sfd=0x555555ae4420, sf=0x555555d318e0, had_sf_layer_cnt=1) at ../fontforge/sfd.c:5365
#2  0x00007ffff7aeb9be in SFD_GetFont
    (sfd=0x555555ae4420, cidmaster=0x0, tok=0x7fffffffc340 "BeginChars:", fromdir=0, dirname=0x555555c4e110 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", sfdversion=3) at ../fontforge/sfd.c:8995
#3  0x00007ffff7aec0aa in SFD_Read
    (filename=0x555555c4e110 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", sfd=0x555555ae4420, fromdir=0)
    at ../fontforge/sfd.c:9088
#4  0x00007ffff7aec2ca in _SFDRead
    (filename=0x555555c4e110 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", sfd=0x555555ae4420)
    at ../fontforge/sfd.c:9121
#5  0x00007ffff7b183cd in _ReadSplineFont
    (file=0x555555ae4420, filename=0x555555ce7f10 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", openflags=(unknown: 0)) at ../fontforge/splinefont.c:1179
#6  0x00007ffff7b194b4 in ReadSplineFont
    (filename=0x555555ce7f10 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", openflags=(unknown: 0))
    at ../fontforge/splinefont.c:1322
#7  0x00007ffff7b19768 in LoadSplineFont
    (filename=0x7fffffffcf70 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", openflags=(unknown: 0))
    at ../fontforge/splinefont.c:1380
#8  0x00007ffff792ee9d in ViewPostScriptFont
    (filename=0x7fffffffcf70 "/home/osboxes/Workspace/some-time-later/Some Time Later.sfd", openflags=0)
    at ../fontforge/fontviewbase.c:1348
#9  0x000055555582058f in fontforge_main (argc=2, argv=0x7fffffffe098) at ../fontforgeexe/startui.c:1389
#10 0x00005555555ac4ad in main (argc=2, argv=0x7fffffffe098) at ../fontforgeexe/main.c:33
```
```
(gdb) p map
$1 = (EncMap *) 0x555555d76730
(gdb) p enc
$2 = -8796
```

I'll look into it and hopefully fix it. I think the recent CID map work broke it.

Crashes the same way on both Xubuntu 20.04 and Windows 10.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Apparently this can happen sometimes, perhaps only on old versions, when
using the "Merge Fonts" feature.

Close #4427

Cf. https://github.com/ctrlcctrlv/some-time-later/commit/82f80d03cb947d53eab08df2d3e854695dad4897

If you encounter this issue, you'll need to manually edit your SFD like
that to see your glyphs in FontView; this only prevents crash.

### Type of change

- **Bug fix**

### CODE REVIEW

File: fontforge/sfd.c [hunk 1]
```diff
@@ -4843,7 +4843,7 @@ return;
     }
     if ( enc>=map->enccount )
 	map->enccount = enc+1;
-    if ( enc!=-1 )
+    if ( enc>=-1 )
```
Comment (skef) [inline fontforge/sfd.c:4846]: Shouldn't this be `enc>=0`?

Comment (ctrlcctrlv) [reply fontforge/sfd.c:4846]: No, because `.notdef` frequently is U+0000

Comment (skef) [reply fontforge/sfd.c:4846]: `enc!=-1` is false when enc is -1. `enc>=-1` is true when enc is -1. That's the change I'm asking about.

(Another way of asking: "Shouldn't this be `enc>-1`?")

Comment (ctrlcctrlv) [reply fontforge/sfd.c:4846]: I'm sorry @skef, I'm too tired to answer today, I spent all my energy on a paper about a Unicode character: [[1]](https://raw.githubusercontent.com/ctrlcctrlv/PamudpodUnicodePaper/master/pamudpod.pdf).

Just reading your comment makes me feel like you're right and I'm stupid for (1) even making this mistake and (2) not understanding your comment. Sorry you have to put up with me. :(

Comment (skef) [reply fontforge/sfd.c:4846]: It's no issue -- this is a primary function of code reviews.

**Comment by JoesCat** [comment]
probably insignificant, but for lower powered processors, zero is a more natural value for status flags - examples, jz, jh, jl, jle, ....
>=0
vs
>-1

**Comment by skef** [comment]
@JoesCat even for inequalities?

**Comment by JoesCat** [comment]
> @JoesCat even for inequalities?

greater that, less than apparently got swallowed - seems this firefox is also pretty-much outdated too. ...probably about time to replace the graphics, or the entire PC. :-)

..there are two flags of interest, Zero and Sign, so between them there is plenty that surrounds zero. jz, jnz, jle, jge, jl, jg, jp, jm
Seeing the patch got merged, seems insignificant to chase this.
