### PR TITLE
Multiple warnings dialogue text selection bug fixes

### LINKED ISSUE #4110: Segmentation fault in _GGDKDraw_TransmitSelection
Follow the steps in #4109, then, keep pressing &laquo;Apply&raquo; until the &laquo;Warnings&raquo; dialog fills to the brim with messages, which in that case should be "Warning: Left contour did not close". Select text in the warnings dialog, which should be scrolled to the bottom, and move your mouse above the dialog, such that you're now selecting text conceptually _above_ the visible text, along with the visible text.

```
Program received signal SIGSEGV, Segmentation fault.
0x0000155553c366f5 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553c366f5 in __strlen_avx2 () at /usr/lib/libc.so.6
#1  0x0000555555831054 in genutf8data (_ed=0x555555ab19a0 <errdata>, len=0x7fffffffcf40) at ../fontforgeexe/uiutil.c:450
#2  0x000055555586310b in _GGDKDraw_TransmitSelection (gdisp=0x555555be1530, e=0x555555bc79f0) at ../gdraw/ggdkdraw.c:153
#3  0x000055555586632a in _GGDKDraw_DispatchEvent (event=0x555555bc79f0, data=0x555555be1530) at ../gdraw/ggdkdraw.c:1219
#4  0x0000155554187954 in  () at /usr/lib/libgdk-3.so.0
#5  0x0000155554134904 in  () at /usr/lib/libgdk-3.so.0
#6  0x0000155553d0839e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#7  0x0000155553d0a1b1 in  () at /usr/lib/libglib-2.0.so.0
#8  0x0000155553d0a1f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#9  0x0000555555869215 in GGDKDrawEventLoop (gdisp=0x555555be1530) at ../gdraw/ggdkdraw.c:2204
#10 0x0000555555854c9d in GDrawEventLoop (gdisp=0x555555be1530) at ../gdraw/gdraw.c:784
#11 0x0000555555818f30 in fontforge_main (argc=2, argv=0x7fffffffe498) at ../fontforgeexe/startui.c:1415
#12 0x00005555555aab89 in main (argc=2, argv=0x7fffffffe498) at ../fontforgeexe/main.c:33
```

```
(gdb) frame 1
#1  0x0000555555831054 in genutf8data (_ed=0x555555ab19a0 <errdata>, len=0x7fffffffcf40) at ../fontforgeexe/uiutil.c:450
450	   cnt = strlen(errdata.errlines[l]+s_c)+1;
(gdb) p errdata
$1 = {errlines = {0x555555df1aa0 "Warning: Left contour did not close", 0x555556413b10 "Warning: Left contour did not close", 
    0x555555df3cc0 "Warning: Left contour did not close", 0x555555d1c410 "Warning: Left contour did not close", 
    0x555555df57f0 "Warning: Left contour did not close", 0x5555564142f0 "Warning: Left contour did not close", 
    0x555555d7b2f0 "Warning: Left contour did not close", 0x555555e7d980 "Warning: Left contour did not close", 
    0x555555f5b080 "Warning: Left contour did not close", 0x555555f5f230 "Warning: Left contour did not close", 
    0x555555ddfe50 "Warning: Left contour did not close", 0x555555f5efc0 "Warning: Left contour did not close", 
    0x555555df49f0 "Warning: Left contour did not close", 0x5555564142c0 "Warning: Left contour did not close", 
    0x555555f58280 "Warning: Left contour did not close", 0x555555f5ffb0 "Warning: Left contour did not close", 
    0x0 <repeats 384 times>}, font = 0x555555f0d6b0, fh = 15, as = 13, vsb = 0x555555f5a990, gw = 0x555555f5ba10, 
  v = 0x555555f5b7e0, cnt = 16, linecnt = 8, offtop = 8, showing = 1, start_l = 15, start_c = 35, end_l = -42, end_c = 0, down = 0}
(gdb) p l
$2 = -42
(gdb) p errdata.errlines[-42]
$3 = 0x0
```

2020-01-27-155827_1066x343_scrot

### PR DESCRIPTION
**Pull request by jtanx**
Fixes #4110

* Prevent negative selection index
* Fix selecting text from right to left on the same line
* Fix null termination when setting clipboard data
* Fix the highlighting of the text
  - Fix typo s_c -> e_c
  - Match up the highlighted area to what actually gets copied (e_c - 1)

### Type of change
- **Bug fix**

BTW this is more easily reproducible with

```py
for i in range(10):
  fontforge.logWarning("blah " * 5)
```

### CODE REVIEW

File: fontforgeexe/uiutil.c [hunk 1]
```diff
@@ -479,8 +486,8 @@ static void MouseToPos(GEvent *event,int *_l, int *_c) {
 	GDrawLayoutInit(errdata.v,errdata.errlines[l],-1,NULL);
 	c = GDrawLayoutXYToIndex(errdata.v,event->u.mouse.x-3,4);
     }
-    *_l = l;
-    *_c = c;
+    *_l = l < 0 ? 0 : l;
```
Comment (jtanx) [inline fontforgeexe/uiutil.c]: This is what fixes the crash

File: fontforgeexe/uiutil.c [hunk 2]
```diff
@@ -593,13 +604,7 @@ return( true );
 	    }
 	}
       break;
-      case et_selclear:
-	errdata.start_l = errdata.end_l = -1;
```
Comment (jtanx) [inline fontforgeexe/uiutil.c]: I believe this was klipper taking over the selection and sending FF this message, which clears out the selected text. But I think it's better to just leave the selection as-is until the user manually clears it by clicking again in the warnings dialogue.

Comment (ctrlcctrlv) [reply fontforgeexe/uiutil.c]: Oh! Yes, I am guilty of using KDE. Sorry about that! Didn't think it mattered.

File: fontforgeexe/uiutil.c [hunk 3]
```diff
@@ -528,27 +535,31 @@ return( GGadgetDispatchEvent(errdata.vsb,event));
       case et_expose:
```
Comment (skef) [inline fontforgeexe/uiutil.c]: leaving this stuff in the switch for future compatibility? (At present `if ( event->type == et_expose ) {` would be simpler.)

File: fontforgeexe/uiutil.c [hunk 4]
```diff
@@ -528,27 +535,31 @@ return( GGadgetDispatchEvent(errdata.vsb,event));
...
 		      GDrawLayoutIndexToPos(gw,s_c,&pos);
 		      xs = pos.x+3;
 		  }
-		  if ( i+errdata.offtop < e_l )
+		  if ( j < e_l )
 		      xe = 3000;
 		  else {
 		      GRect pos;
-		      GDrawLayoutIndexToPos(gw,s_c,&pos);
+		      GDrawLayoutIndexToPos(gw,e_c-1,&pos);
```
Comment (skef) [inline fontforgeexe/uiutil.c]: Not sure I understand this change, but not in the sense that I think something is wrong with it.

File: fontforgeexe/uiutil.c (hunk 3 above)
Comment (jtanx) [reply fontforgeexe/uiutil.c]: Oh I didn't even spot that when working on this. I think I'll leave it anyway, given it's the usual pattern for working with events.

File: fontforgeexe/uiutil.c (hunk 4 above)
Comment (jtanx) [reply fontforgeexe/uiutil.c]: Basically this highlight is inclusive, but the copy-to-clipboard routine uses the end column as exclusive, so it's just aligning the two so that what you select matches what gets copied.

Comment (skef) [reply fontforgeexe/uiutil.c]: So was it just broken before?

Comment (jtanx) [reply fontforgeexe/uiutil.c]: Well originally there was a typo so it was using `s_c` instead, so you'd see the end position tracking your cursor when selecting text. So yeah it was pretty broken

Comment (skef) [reply fontforgeexe/uiutil.c]: Ah, good -- the switch was what I didn't understand. 

I've already approved but consider this PR fully approved at this point.

Comment (skef) [reply fontforgeexe/uiutil.c]: Oh , I guess I should have read the description better. *sigh*
