### PR TITLE
If converting UTF-8⇔UTF-8, use existing functions

### LINKED ISSUE #4159: GFileChooser segmentation fault when going to directory with certain filenames
Caught while looking into https://github.com/fontforge/fontforge/issues/2475#issuecomment-583849612

This is a tracking issue, I plan to fix this today

Steps to reproduce:

1. Extract [fonts-richstyle_0.4.tar](https://richstyle.org/downloads/src/fonts-richstyle_0.4.tar) to `/tmp`
2. New font, any glyph
3. Go to directory `/tmp/fonts-richstyle_0.4/SVGs/`
4. Make sure type is SVG&hellip;
5. Crash!

Note: This crash only happens if `LC_ALL` is a UTF-8 one, like `en_US.UTF-8`

```
(gdb) bt
#0  0x0000155553b2114c in strcoll_l () at /usr/lib/libc.so.6
#1  0x00005555558c2bf0 in GTextInfoCompare (ti1=0x555555e267b0, ti2=0x555555e267f0) at ../gdraw/gtextinfo.c:718
#2  0x000055555586ead3 in GListAlphaCompare (v1=0x555555e25eb0, v2=0x555555e25eb8) at ../gdraw/glist.c:124
#3  0x0000155553acc605 in msort_with_tmp.part () at /usr/lib/libc.so.6
#4  0x0000155553acc592 in msort_with_tmp.part () at /usr/lib/libc.so.6
#5  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#6  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#7  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#8  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#9  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#10 0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#11 0x0000155553acc936 in qsort_r () at /usr/lib/libc.so.6
#12 0x000055555586eb15 in GListOrderIt (gl=0x555555dff190) at ../gdraw/glist.c:128
#13 0x000055555586fe4a in GListSetList (g=0x555555dff190, ti=0x555555e25ea0, docopy=0) at ../gdraw/glist.c:425
#14 0x00005555558623c9 in GGadgetSetList (g=0x555555dff190, ti=0x555555e25ea0, copyit=0) at ../gdraw/ggadgets.c:1291
#15 0x00005555558584bb in GFileChooserFillList (gfc=0x555555c8a2c0, first=0x555555db3050, dir=0x555555e364f0) at ../gdraw/gfilechooser.c:367
#16 0x0000555555858609 in GFileChooserReceiveDir (gc=0x555555e250f0) at ../gdraw/gfilechooser.c:389
#17 0x0000155554e0357a in _gio_file_dir (gc=0x555555e250f0, path=0x555555e11d80 "/tmp/fonts-richstyle_0.4/SVGs/") at ../gutils/giofile.c:182
#18 0x0000155554e03a10 in _GIO_localDispatch (gc=0x555555e250f0) at ../gutils/giofile.c:254
#19 0x0000155554e02bc9 in GIOdispatch (gc=0x555555e250f0, gf=gf_dir) at ../gutils/gio.c:144
#20 0x0000155554e02c51 in GIOdir (gc=0x555555e250f0) at ../gutils/gio.c:161
#21 0x0000555555858c8a in GFileChooserScanDir (gfc=0x555555c8a2c0, dir=0x555555dd9b60) at ../gdraw/gfilechooser.c:479
#22 0x000055555585bfca in GFileChooserRefreshList (g=0x555555c8a2c0) at ../gdraw/gfilechooser.c:1342
#23 0x0000555555665b85 in GFD_Format (g=0x555555e122e0, e=0x7fffffffbcc0) at ../fontforgeexe/cvimportdlg.c:541
#24 0x0000555555846a38 in GListButtonSelected (g=0x555555e122e0, i=3) at ../gdraw/gbuttons.c:1149
#25 0x000055555587253e in popup_eh (popup=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/glist.c:1074
#26 0x000055555584f8a7 in _GWidget_Container_eh (gw=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/gcontainer.c:405
#27 0x0000555555850e68 in _GWidget_TopLevel_eh (gw=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/gcontainer.c:747
#28 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e176e0, event=0x7fffffffbfb0, eh=0x5555558504da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#29 0x000055555586945e in GGDKDrawPostEvent (e=0x7fffffffbfb0) at ../gdraw/ggdkdraw.c:2224
#30 0x0000555555854e2c in GDrawPostEvent (e=0x7fffffffbfb0) at ../gdraw/gdraw.c:791
#31 0x000055555586e78c in GListSelected (l=0x555555e09f40, frommouse=1, index=3) at ../gdraw/glist.c:51
#32 0x0000555555870bfc in glist_mouse (g=0x555555e09f40, event=0x7fffffffc2d0) at ../gdraw/glist.c:599
#33 0x000055555584efe8 in _GWidget_Container_eh (gw=0x555555e176e0, event=0x7fffffffc2d0) at ../gdraw/gcontainer.c:304
#34 0x0000555555850e68 in _GWidget_TopLevel_eh (gw=0x555555e176e0, event=0x7fffffffc2d0) at ../gdraw/gcontainer.c:747
#35 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e176e0, event=0x7fffffffc2d0, eh=0x5555558504da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#36 0x00005555558665ab in _GGDKDraw_DispatchEvent (event=0x555555bbb510, data=0x555555bd56c0) at ../gdraw/ggdkdraw.c:1237
#37 0x0000155554140954 in  () at /usr/lib/libgdk-3.so.0
#38 0x00001555540ed904 in  () at /usr/lib/libgdk-3.so.0
#39 0x0000155553cc139e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#40 0x0000155553cc31b1 in  () at /usr/lib/libglib-2.0.so.0
#41 0x0000155553cc31f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x00005555558692d9 in GGDKDrawProcessOneEvent (gdisp=0x555555bd56c0) at ../gdraw/ggdkdraw.c:2193
#43 0x0000555555854d00 in GDrawProcessOneEvent (gdisp=0x555555bd56c0) at ../gdraw/gdraw.c:764
#44 0x0000555555666de2 in _Import (cv=0x15554f1e7010, bv=0x0, fv=0x0) at ../fontforgeexe/cvimportdlg.c:783
#45 0x0000555555666e3c in CVImport (cv=0x15554f1e7010) at ../fontforgeexe/cvimportdlg.c:788
#46 0x0000555555608f6d in CVMenuImport (gw=0x555555da2a90, UNUSED_mi=0x555555da4fe0, UNUSED_e=0x7fffffffcff0) at ../fontforgeexe/charview.c:6775
#47 0x00005555558822ed in gmenu_mouse (m=0x555555ba8660, event=0x7fffffffcff0) at ../gdraw/gmenu.c:948
#48 0x0000555555883db0 in gmenu_eh (w=0x555555e0ee60, ge=0x7fffffffcff0) at ../gdraw/gmenu.c:1389
#49 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e0ee60, event=0x7fffffffcff0, eh=0x555555883cd7 <gmenu_eh>) at ../gdraw/ggdkdraw.c:334
#50 0x00005555558665ab in _GGDKDraw_DispatchEvent (event=0x555555dee8e0, data=0x555555bd56c0) at ../gdraw/ggdkdraw.c:1237
#51 0x0000155554140954 in  () at /usr/lib/libgdk-3.so.0
#52 0x00001555540ed904 in  () at /usr/lib/libgdk-3.so.0
#53 0x0000155553cc139e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#54 0x0000155553cc31b1 in  () at /usr/lib/libglib-2.0.so.0
#55 0x0000155553cc31f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#56 0x0000555555869355 in GGDKDrawEventLoop (gdisp=0x555555bd56c0) at ../gdraw/ggdkdraw.c:2204
#57 0x0000555555854ddd in GDrawEventLoop (gdisp=0x555555bd56c0) at ../gdraw/gdraw.c:784
#58 0x0000555555819001 in fontforge_main (argc=2, argv=0x7fffffffe438) at ../fontforgeexe/startui.c:1415
#59 0x00005555555aab89 in main (argc=2, argv=0x7fffffffe438) at ../fontforgeexe/main.c:33
```

The problem is a comparison at frame 2:

```
(gdb) frame
#2  0x000055555586ead3 in GListAlphaCompare (v1=0x555555e25eb0, v2=0x555555e25eb8) at ../gdraw/glist.c:124
124	return( GTextInfoCompare(*pt1,*pt2));
(gdb) wc ((**pt1).text)
"[d83d][dec0].svg"
(gdb) wc ((**pt2).text)
"[e001].svg"
```

This calls, at frame 1, `strcoll`, which relies on the return value of `u2utf8_copy`, which in turn relies on `utf8_ipdb`, which returns an error if any PUA character is detected! That's simply the wrong thing to do, and I don't know why George thought otherwise.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
The versions at these points were non-standard conforming, and encoded characters as surrogate pairs if possible, even though surrogate pairs are explicitly forbidden in UTF-8.

https://unicodebook.readthedocs.io/issues.html#non-strict-utf-8-decoder-overlong-byte-sequences-and-surrogates

(It took me more than three hours to come up with this solution, as I had to check basically all the code that could possibly corrupt this, and I wasted the first hour thinking that the filenames _themselves_ had the problem.)

This closes #4159, which contains a test case. But in short, the easiest way to test this now that I know the problem is to just make a file named an emoji and observe the crash.

### Type of change

- **Bug fix**

### CODE REVIEW

File: Unicode/ustring.c [hunk 1]
```diff
@@ -562,12 +562,12 @@ void utf82u_strcat(unichar_t *to,const char *from) {
...
 
-char *u2utf8_strcpy(char *utf8buf,const unichar_t *ubuf) {
+char *u2utf8_strncpy(char *utf8buf,const unichar_t *ubuf,int len) {
 /* Copy unichar string 'ubuf' into utf8 buffer string 'utf8buf' */
     char *pt = utf8buf;
 
     if ( ubuf!=NULL ) {
-	while ( *ubuf && (pt=utf8_idpb(pt,*ubuf++,0)) );
+	while ( *ubuf && (pt=utf8_idpb(pt,*ubuf++,0)) && --len );
 	if ( pt ) {
```
Comment (skef) [inline Unicode/ustring.c]: I dunno what the thought behind this was, but `utf8_idpb()` assigns to the argument corresponding to `pt`, and then increments, without checking whether its null. So this conditional seems useless to me -- it's not like the pointer is likely to wrap around to zero in just the right place. 

Better to assert utf8buf isn't at the top (for debug) and remove the conditional.

File: Unicode/ustring.c [hunk 2]
```diff
@@ -576,6 +576,10 @@ char *u2utf8_strcpy(char *utf8buf,const unichar_t *ubuf) {
     return( NULL );
 }
 
+char *u2utf8_strcpy(char *utf8buf,const unichar_t *ubuf) {
+    return u2utf8_strncpy(utf8buf, ubuf, u_strlen(ubuf));
```
Comment (skef) [inline Unicode/ustring.c]: Now we're looping twice for `u2utf8_strcpy()`, once to get the length to pass in and once to copy the chars. Almost every code review comment is about tidying up; time to feel dirty. 

Take a deep breath, in/out.

Now: consider passing -1 as the length here.

File: Unicode/ustring.c (hunk 1 above)
Comment (skef) [reply Unicode/ustring.c]: no -- assert *`utf8buf`* is not NULL, not `ubuf`. Leave the outer guard on `ubuf`, it might indeed be null. It's the inner `pt` guard that I think is useless.

Comment (ctrlcctrlv) [reply Unicode/ustring.c]: Sorry, I'll fix it :)

Comment (ctrlcctrlv) [reply Unicode/ustring.c]: This time I looked at it longer, I think it's what you're asking for now

File: Unicode/ustring.c [hunk 3]
```diff
@@ -562,20 +563,27 @@ void utf82u_strcat(unichar_t *to,const char *from) {
...
+    assert(utf8buf != NULL);
+
     if ( ubuf!=NULL ) {
-	while ( *ubuf && (pt=utf8_idpb(pt,*ubuf++,0)) );
-	if ( pt ) {
-	    *pt = '\0';
-	    return( utf8buf );
-	}
+        while ( *ubuf && (--len != 0) ) {
+            pt=utf8_idpb(pt,*ubuf++,0);
```
Comment (skef) [inline Unicode/ustring.c]: I didn't think about the loop restructuring but it does improve the code given the assert. The original author probably put things in that form thinking it protected against `pt==NULL` but it doesn't unless `utf8_idpb` does. 

Anyway this looks good to me. (I assume it passes our unit tests?)

Comment (ctrlcctrlv) [reply Unicode/ustring.c]: Yup, it does. I'm going to merge exactly this, but I'm going to force push my branch to consolidate the last three commits into one commit. That way we have separate commits for the Git history of (1) removing the second UTF-8 decoder implementation and (2) adding the new function. So if you see new commits, they aren't really new.
