### PR TITLE
Modernize fixed pitch flag computation

### LINKED ISSUE #5489: Ufo3 export of monospace fonts does not set postisfixedpitch to true
When a sfd file is exported to ufo, if the font is selected as monospace, fontinfo.plist file should contain following key
```
<key>postscriptIsFixedPitch</key>
                <true/>
```
However the generated ufo do not contain such key.

### PR DESCRIPTION
**Pull request by iorsh**
This PR allows monospace fonts with modern features
* Zero-width glyphs are allowed, such as control characters or diacritical marks
* Dual-width glyphs are alowed, such as emojis or kanij

Fixes #5489

### CODE REVIEW

**Comment by iorsh** [comment]
CI is a gift that keeps on giving... Libspiro is broken on Windows.

@JoesCat, do you know just in case what could have happened?

**Comment by JoesCat** [comment]
On December 6, 2024 12:06:24 AM Maxim Iorsh wrote:
> Looks like the CI issue is not about Spiro, but rather broken `pacman` -
> see https://github.com/jtanx/fontforgebuilds/pull/22

repology shows several distros haven't upgraded to libspiro 2024 so there 
will likely be more faults reported due to libspiro 2022 (which is faulty).

**Comment by JoesCat** [comment]
mingw may also be gradually sliding away from 32bit. I noted reading a request to upgrade something to help with gimp3 which wasn't built for 32bit, but was for 64bit.

File: fontforge/splinesave.c [hunk 1]
```diff
@@ -2074,7 +2112,7 @@ struct pschars *SplineFont2ChrsSubrs(SplineFont *sf, int iscjk,
 	dummynotdef.parent = sf;
 	dummynotdef.layer_cnt = sf->layer_cnt;
 	dummynotdef.layers = calloc(sf->layer_cnt,sizeof(Layer));
-	dummynotdef.width = SFOneWidth(sf);
+	dummynotdef.width = CIDOneWidth(sf);
```
Comment (skef) [inline fontforge/splinesave.c:2115]: If we're using this function in these updated cases, should the final function name be SFOneWidth again?

Comment (iorsh) [reply fontforge/splinesave.c]: Agree, renamed.

**Comment by Finii** [comment]
> This PR allows monospace fonts with modern features
> 
>     * Zero-width glyphs are allowed, such as control characters or diacritical marks
> 
>     * Dual-width glyphs are alowed, such as emojis or kanij

Well, the different-from-monospaced-width widths are not written out to a `ttf` file; `otf` works.
`tottf` does not allow different width for individual glyphs if `isFixedPitch` is active.

`tottf` exports only the widths of the first 4 glyphs, beginning with the 3 magic glyphs.

So even if the 4th glyph has 'normal' width, there will be no zero and no dual width glyphs in `ttf`s.
The PR above handles the more severe case with the 4th glyph has zero width :grimacing: and of course also the general case.

_Edit: Add last paragraph_
