### PR TITLE
Make number of chars openable in MetricsView from CharView configurable

### LINKED ISSUE #4114: The maximum number of characters openable in the MetricsView from the CharView should be configurable
Title says it all. I plan to open a PR which fixes this so am just opening this so I can close an issue.

The problem is that charview.c:6713, which calls `MetricsViewCreate`, uses a fixed size buffer (metricsview.c:5185), with the helpful comment "max. chars picked up: 15."

I will make it so that it can be set to 0, which will mean, "never show a character when opened from CharView", and -1, which will mean "always attempt to show all characters selected in MetricsView, even if this might crash FontForge due to lack of memory or freeze up the interface in large fonts"

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Close #4114. More useful than it sounds. Fifteen characters is far too few.

### Type of change

- **Non-breaking change**

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Please do not merge or review. I made a big mistake which I have caught. I will force push shortly. Then I'll delete this post.

File: fontforgeexe/metricsview.c [hunk 1]
```diff
@@ -5181,8 +5183,11 @@ MetricsView *MetricsViewCreate(FontView *fv,SplineChar *sc,BDFFont *bdf) {
     FontRequest rq;
     static GWindow icon = NULL;
     extern int _GScrollBar_Width;
-    // Max. glyphname length: 31, max. chars picked up: 15. 31*15 = 465
-    char buf[465], *pt;
+    // The maximum length of a glyph's name is 31 chars.
+#define MAXGLYPHNAME_LEN 31
+    unsigned int selectmax = fvmv_selectmax < 0 ? fv->b.sf->glyphcnt : fvmv_selectmax;
+    char buf[selectmax * MAXGLYPHNAME_LEN], *pt;
+    char titlebuf[50+strlen(fv->b.sf->fontname)+1];
```
Comment (jtanx) [inline fontforgeexe/metricsview.c]: Let's avoid VLAs like this, just malloc it. This can easily lead to a stack overflow depending on how large this is.

**Comment by ctrlcctrlv** [comment]
@frank-trampe The change you made to the project settings where merges can't be made unless "1 approving review is required by reviewers with write access" is continuing to cause more and more PRs to build up. This PR has been reviewed, the problem has been fixed, but it has sat here for three days because of this constraint.

It's not even pushable via CLI:

```
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 2.02 KiB | 2.02 MiB/s, done.
Total 8 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/fontforge/fontforge
 ! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/fontforge/fontforge'
```

The irony of my own issue (#4081) causing me to lose write access is not lost on me. Are you trying to teach me a lesson? Because if so it's not really me that's suffering, this whole new system is backwards. Imagine if yesterday I'd merged #4097 without finding the bug I found in it. (Let's just imagine @jtanx did not comment in this scenario.) I wouldn't be able to revert it.

Please give me a real explanation as to why I can no longer push, or restore that ability. There are 11 open PRs now, this is getting ridiculous

**Comment by jtanx** [comment]
I relaxed the approval restriction, but only because it was never an issue in the past (so don't make it an issue now ;)). fwiw prior to those changes, I already had enforced branch protections on the master branch that prevents force pushing and direct pushes to it.


oh and I haven't actually reviewed this, I just glanced at it and spotted an issue.

**Comment by ctrlcctrlv** [comment]
Thank you, I will not make it an issue :-)

**Comment by frank-trampe** [comment]
Hehe. Sometimes it takes a little iteration to arrive at the right solution.
