### PR TITLE
Fix for #3347 SIGSEGV on trying to Merge CID Font

### LINKED ISSUE #3347: SIGSEGV on trying to Merge CID Font (Noto Sans Japanese) into other font
When merging Noto Sans Japanese into other font (Noto Sans Latin for example), I get a crash in fvfonts.c:1049 (in FVMergeRefigureMapSel). The issue seems to be that for a lot of characters, `o_sf->glyphs[i]` is NULL. 

I'm not really capable of fixing the error. Instead a working workaround seems to be to flatten the font before merging. Confirmed on current git master (9e9278c66ecc47290accb4e9e4aff82e8578ce1e) at the time, on both Linux and OSX. Also confirmed on version "19:05 UTC 30-Jul-2017" on OSX.

Reproduce, in i.e. Python:

    font = fontforge.open('NotoSans-Bold.ttf')
    font.mergeFonts('Noto-Sans-Japanese-Bold.ttf')

[fonts.zip](https://github.com/fontforge/fontforge/files/2477654/fonts.zip)

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

### PR DESCRIPTION
**Pull request by skef**
Closes #3347 . See that issue for analysis. 

This should definitely be reviewed by someone more familiar with CID Fonts and their implications than I am. For convenience I'm including my test script, an `.sfd` saved after the merge and a `.ttf` generated after the merge in this zip: [bug3347.zip](https://github.com/fontforge/fontforge/files/2743972/bug3347.zip)

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

.

### CODE REVIEW

**Comment by frank-trampe** [comment]
@skef, there are some odd whitespace changes that make it difficult to see what actually changed. Could you perhaps use GitHub comments to annotate and to explain actual changes? Otherwise, I would need to perform a zero-based review on the code, which would be very tedious.

File: fontforge/fvfonts.c [hunk 1]
```diff
@@ -1079,62 +1079,60 @@ static void FVMergeRefigureMapSel(FontViewBase *fv,SplineFont *into,SplineFont *
...
     mapping = malloc(other->glyphcnt*sizeof(int));
-    memset(mapping,-1,other->glyphcnt*sizeof(int));
+    for (i = 0; i<other->glyphcnt; ++i)
+	mapping[i] = -1;
 
     bitmap_into = into->cidmaster!=NULL? into->cidmaster : into;
 
+    /* If other starts as CID it should be flattened before calling */
+    cnt = 0;
     for ( doit=0; doit<2; ++doit ) {
```
Comment (skef) [inline fontforge/fvfonts.c]: Everything below to (green) line 1135 is the same except that the `do ... while()` loop level is removed. The code used to "loop once" with `other` if there were no subfonts and over the subfonts if there were. The new code just uses other as the font. `o_sf` is accordingly eliminated and that string replaced with `other`.

File: fontforge/fvfonts.c [hunk 2]
```diff
@@ -1256,8 +1254,11 @@ return;
     /*  If both are CID then merge each subfont separately */
     if ( fv->sf->cidmaster!=NULL && other->subfonts!=NULL )
 	CIDMergeFont(fv->sf->cidmaster,other,preserveCrossFontKerning);
-    else
+    else {
+	if (other->subfonts!=NULL)
```
Comment (skef) [inline fontforge/fvfonts.c]: Here we flatten if there are subfonts as the comment on (old) line 1254 suggests. 

I take it that the loop level I removed was intended do be equivalent to what `SFFlatten()` does, and perhaps faster or better in some other way. I discuss in the comments on #3347 why the code doesn't work and would be difficult to make work.

File: fontforgeexe/fontview.c [hunk 3]
```diff
@@ -7120,7 +7120,7 @@ static void FontView_ReformatAll(SplineFont *sf) {
     MetricsView *mvs;
     extern int use_freetype_to_rasterize_fv;
 
-    if ( ((FontView *) (sf->fv))->v==NULL || ((FontView *) (sf->fv))->colcnt==0 )			/* Can happen in scripts */
+    if ( sf->fv==NULL || ((FontView *) (sf->fv))->v==NULL || ((FontView *) (sf->fv))->colcnt==0 )			/* Can happen in scripts */
```
Comment (skef) [inline fontforgeexe/fontview.c]: This function was called as a side-effect of `SFFlatten()` and wasn't quite set up to be run without a UI.

**Comment by skef** [comment]
> Wait, so does this drop the [broken] code path for merging a CID font into a CID font without flattening?

If I understand your question correctly the answer is no. This change only affects the merge of a CID font with a non-CID font. The case of merging two CID fonts is caught and addressed (how well I don't know) by lines 1257-8 of the existing code and 1255-6 of the new code, which are unchanged.

**Comment by frank-trampe** [comment]
Ah, I see. So `_MergeFont` drops flattening, and we just flattening the incoming font when in that code path?

**Comment by skef** [comment]
> Ah, I see. So `_MergeFont` drops flattening, and we just flattening the incoming font when in that code path?

Yes, that is the essence of the fix.

**Comment by frank-trampe** [comment]
The changes look fine to me in that context. Given the complexity, I'd like @jtanx to double-check before we merge.

File: fontforge/fvfonts.c [hunk 4]
```diff
@@ -1079,62 +1079,60 @@ static void FVMergeRefigureMapSel(FontViewBase *fv,SplineFont *into,SplineFont *
...
+    SplineFont *bitmap_into;
     BDFFont *bdf;
     FontViewBase *fvs;
     int *mapping;
 
     emptypos = into->glyphcnt;
+
     mapping = malloc(other->glyphcnt*sizeof(int));
-    memset(mapping,-1,other->glyphcnt*sizeof(int));
+    for (i = 0; i<other->glyphcnt; ++i)
```
[the remark this answers is not in the document]
Comment (jtanx) [reply fontforge/fvfonts.c]: As mentioned in #3347, memsetting to `-1` should work just fine.
