### PR TITLE
Misc CVE fixes

### LINKED ISSUE #4084: Use-after-free (heap) in the SFD_GetFontMetaData() function
Hi,

While fuzzing FontForge with AFL, I found a heap use-after-free in the SFD_GetFontMetaData() function, in sfd.c.

Attaching a reproducer (gzipped so GitHub accepts it): [test01.sfd.gz](https://github.com/fontforge/fontforge/files/4019970/test01.sfd.gz)

Issue can be reproduced in FontForge 20190801 and with latest Git master by running:

```
fontforge test01.sfd
```

```
=================================================================
==7418==ERROR: AddressSanitizer: heap-use-after-free on address 0x6030000c8068 at pc 0x7f60f1122f2d bp 0x7fff16e6ff70 sp 0x7fff16e6f718
WRITE of size 48 at 0x6030000c8068 thread T0
    #0 0x7f60f1122f2c  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x67f2c)
    #1 0x7f60ef2c7850 in SFD_GetFontMetaData /home/fcambus/fontforge-20190801/fontforge/sfd.c:8008
    #2 0x7f60ef2ccf66 in SFD_GetFont /home/fcambus/fontforge-20190801/fontforge/sfd.c:8502
    #3 0x7f60ef2d3e0f in SFD_Read /home/fcambus/fontforge-20190801/fontforge/sfd.c:9077
    #4 0x7f60ef2d4360 in _SFDRead /home/fcambus/fontforge-20190801/fontforge/sfd.c:9110
    #5 0x7f60ef32d7bd in _ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1178
    #6 0x7f60ef32f0bf in ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1321
    #7 0x7f60ef32f591 in LoadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1379
    #8 0x7f60eeeedbbc in ViewPostScriptFont /home/fcambus/fontforge-20190801/fontforge/fontviewbase.c:1347
    #9 0x7f60f0d3c89e in fontforge_main /home/fcambus/fontforge-20190801/fontforgeexe/startui.c:1392
    #10 0x557137b971ec in main /home/fcambus/fontforge-20190801/fontforgeexe/main.c:33
    #11 0x7f60f03c81e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #12 0x557137b9710d in _start (/home/fcambus/fontforge-20190801/fontforgeexe/.libs/fontforge+0x110d)

0x6030000c8070 is located 0 bytes to the right of 32-byte region [0x6030000c8050,0x6030000c8070)
freed by thread T0 here:
    #0 0x7f60f11c86ef in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10d6ef)
    #1 0x7f60ee24c014 in _XReply (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x40014)

previously allocated by thread T0 here:
    #0 0x7f60f11c8ae8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x7f60ed7a3cfd  (/usr/lib/x86_64-linux-gnu/libxcb.so.1+0xdcfd)

SUMMARY: AddressSanitizer: heap-use-after-free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x67f2c) 
Shadow bytes around the buggy address:
  0x0c0680010fb0: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c0680010fc0: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c0680010fd0: fd fd fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c0680010fe0: fd fd fd fa fa fa fd fd fd fd fa fa 00 00 04 fa
  0x0c0680010ff0: fa fa 00 00 00 00 fa fa fd fd fd fa fa fa fd fd
=>0x0c0680011000: fd fd fa fa 00 00 00 fa fa fa fd fd fd[fd]fa fa
  0x0c0680011010: 00 00 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680011020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680011030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680011040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680011050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==7418==ABORTING
```

### LINKED ISSUE #4086: NULL pointer dereference in the SFDGetSpiros() function
Hi,

While fuzzing FontForge with AFL, I found a NULL pointer dereference in the SFDGetSpiros() function, in sfd.c.

Attaching a reproducer (gzipped so GitHub accepts it): [test03.sfd.gz](https://github.com/fontforge/fontforge/files/4021735/test03.sfd.gz)

Issue can be reproduced in FontForge 20190801 and with latest Git master by running:

```
fontforge test03.sfd
```

```
=================================================================
==4457==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ff8c0d8e2bf bp 0x7fffda0289f0 sp 0x7fffda028930 T0)
==4457==The signal is caused by a READ memory access.
==4457==Hint: address points to the zero page.
    #0 0x7ff8c0d8e2be in SFDGetSpiros /home/fcambus/fontforge-20190801/fontforge/sfd.c:4039
    #1 0x7ff8c0d8e876 in SFDGetSplineSet /home/fcambus/fontforge-20190801/fontforge/sfd.c:4083
    #2 0x7ff8c0d9e9f7 in SFDGetChar /home/fcambus/fontforge-20190801/fontforge/sfd.c:5698
    #3 0x7ff8c0dc0f3d in SFD_GetFont /home/fcambus/fontforge-20190801/fontforge/sfd.c:8984
    #4 0x7ff8c0dc1e0f in SFD_Read /home/fcambus/fontforge-20190801/fontforge/sfd.c:9077
    #5 0x7ff8c0dc2360 in _SFDRead /home/fcambus/fontforge-20190801/fontforge/sfd.c:9110
    #6 0x7ff8c0e1b7bd in _ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1178
    #7 0x7ff8c0e1d0bf in ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1321
    #8 0x7ff8c0e1d591 in LoadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1379
    #9 0x7ff8c09dbbbc in ViewPostScriptFont /home/fcambus/fontforge-20190801/fontforge/fontviewbase.c:1347
    #10 0x7ff8c282a89e in fontforge_main /home/fcambus/fontforge-20190801/fontforgeexe/startui.c:1392
    #11 0x559d8dc361ec in main /home/fcambus/fontforge-20190801/fontforgeexe/main.c:33
    #12 0x7ff8c1eb61e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #13 0x559d8dc3610d in _start (/home/fcambus/fontforge-20190801/fontforgeexe/.libs/fontforge+0x110d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fcambus/fontforge-20190801/fontforge/sfd.c:4039 in SFDGetSpiros
==4457==ABORTING
```

### LINKED ISSUE #4088: NULL pointer dereference in the SFD_AssignLookups() function
Hi,

While fuzzing FontForge with AFL, I found a NULL pointer dereference in the SFD_AssignLookups() function, in sfd1.c.

Attaching a reproducer (gzipped so GitHub accepts it): [test04.sfd.gz](https://github.com/fontforge/fontforge/files/4023744/test04.sfd.gz)

Issue can be reproduced in FontForge 20190801 and with latest Git master by running:

```
fontforge test04.sfd
```

```
=================================================================
==2985==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x7fb18974e2e3 bp 0x7ffdf9bc67c0 sp 0x7ffdf9bc6710 T0)
==2985==The signal is caused by a READ memory access.
==2985==Hint: address points to the zero page.
    #0 0x7fb18974e2e2 in SFD_AssignLookups /home/fcambus/fontforge-20190801/fontforge/sfd1.c:678
    #1 0x7fb1897ac2de in SFD_GetFont /home/fcambus/fontforge-20190801/fontforge/sfd.c:9011
    #2 0x7fb1897ace0f in SFD_Read /home/fcambus/fontforge-20190801/fontforge/sfd.c:9077
    #3 0x7fb1897ad360 in _SFDRead /home/fcambus/fontforge-20190801/fontforge/sfd.c:9110
    #4 0x7fb1898067bd in _ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1178
    #5 0x7fb1898080bf in ReadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1321
    #6 0x7fb189808591 in LoadSplineFont /home/fcambus/fontforge-20190801/fontforge/splinefont.c:1379
    #7 0x7fb1893c6bbc in ViewPostScriptFont /home/fcambus/fontforge-20190801/fontforge/fontviewbase.c:1347
    #8 0x7fb18b21589e in fontforge_main /home/fcambus/fontforge-20190801/fontforgeexe/startui.c:1392
    #9 0x560583aae1ec in main /home/fcambus/fontforge-20190801/fontforgeexe/main.c:33
    #10 0x7fb18a8a11e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #11 0x560583aae10d in _start (/home/fcambus/fontforge-20190801/fontforgeexe/.libs/fontforge+0x110d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fcambus/fontforge-20190801/fontforge/sfd1.c:678 in SFD_AssignLookups
==2985==ABORTING
```

### LINKED ISSUE #4089: NULL pointer dereference in the strstrmatch() function
Hi,

While fuzzing FontForge with AFL, I found a NULL pointer dereference in the strstrmatch() function, in char.c.

Attaching a reproducer (gzipped so GitHub accepts it): [test05.sfd.gz](https://github.com/fontforge/fontforge/files/4025472/test05.sfd.gz)

Issue can be reproduced in FontForge 20190801 and with latest Git master by running:

```
fontforge -lang ff -c 'Open("test05.sfd"); Generate("test05.otf")'
```

```
=================================================================
==13449==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fe84086f7a5 bp 0x7ffdb2480f00 sp 0x7ffdb2480ed0 T0)
==13449==The signal is caused by a READ memory access.
==13449==Hint: address points to the zero page.
    #0 0x7fe84086f7a4 in strstrmatch /home/fcambus/fontforge-20190801/Unicode/char.c:84
    #1 0x7fe83ff15681 in SFDefaultOS2Info /home/fcambus/fontforge-20190801/fontforge/tottf.c:3084
    #2 0x7fe83ff37756 in initTables /home/fcambus/fontforge-20190801/fontforge/tottf.c:5704
    #3 0x7fe83ff3c475 in _WriteTTFFont /home/fcambus/fontforge-20190801/fontforge/tottf.c:6143
    #4 0x7fe83ff3c611 in WriteTTFFont /home/fcambus/fontforge-20190801/fontforge/tottf.c:6171
    #5 0x7fe83faef0b4 in _DoSave /home/fcambus/fontforge-20190801/fontforge/savefont.c:845
    #6 0x7fe83faf1f7b in GenerateScript /home/fcambus/fontforge-20190801/fontforge/savefont.c:1269
    #7 0x7fe83fb089c4 in bGenerate /home/fcambus/fontforge-20190801/fontforge/scripting.c:2061
    #8 0x7fe83fb666bb in docall /home/fcambus/fontforge-20190801/fontforge/scripting.c:9632
    #9 0x7fe83fb6755e in handlename /home/fcambus/fontforge-20190801/fontforge/scripting.c:9745
    #10 0x7fe83fb6b8d0 in term /home/fcambus/fontforge-20190801/fontforge/scripting.c:9983
    #11 0x7fe83fb6d1de in mul /home/fcambus/fontforge-20190801/fontforge/scripting.c:10128
    #12 0x7fe83fb6dade in add /home/fcambus/fontforge-20190801/fontforge/scripting.c:10174
    #13 0x7fe83fb6e9e7 in comp /home/fcambus/fontforge-20190801/fontforge/scripting.c:10249
    #14 0x7fe83fb6f44d in _and /home/fcambus/fontforge-20190801/fontforge/scripting.c:10293
    #15 0x7fe83fb6fa79 in _or /home/fcambus/fontforge-20190801/fontforge/scripting.c:10325
    #16 0x7fe83fb70167 in assign /home/fcambus/fontforge-20190801/fontforge/scripting.c:10358
    #17 0x7fe83fb7184f in expr /home/fcambus/fontforge-20190801/fontforge/scripting.c:10436
    #18 0x7fe83fb734de in ff_statement /home/fcambus/fontforge-20190801/fontforge/scripting.c:10649
    #19 0x7fe83fb74b92 in ProcessNativeScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10796
    #20 0x7fe83fb7559f in _CheckIsScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10894
    #21 0x7fe83fb75881 in CheckIsScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10927
    #22 0x7fe8416b2be7 in fontforge_main /home/fcambus/fontforge-20190801/fontforgeexe/startui.c:1099
    #23 0x5575eaf031ec in main /home/fcambus/fontforge-20190801/fontforgeexe/main.c:33
    #24 0x7fe840d401e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #25 0x5575eaf0310d in _start (/home/fcambus/fontforge-20190801/fontforgeexe/.libs/fontforge+0x110d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fcambus/fontforge-20190801/Unicode/char.c:84 in strstrmatch
==13449==ABORTING
```

### LINKED ISSUE #4090: NULL pointer dereference in the dumpcffnames() function
Hi,

While fuzzing FontForge with AFL, I found a NULL pointer dereference in the dumpcffnames() function, in tottf.c.

Attaching a reproducer (gzipped so GitHub accepts it): [test06.sfd.gz](https://github.com/fontforge/fontforge/files/4025578/test06.sfd.gz)

Issue can be reproduced in FontForge 20190801 and with latest Git master by running:

```
fontforge -lang ff -c 'Open("test06.sfd"); Generate("test06.otf")'
```

```
=================================================================
==14023==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f5624395ba5 bp 0x7ffda6285000 sp 0x7ffda6284778 T0)
==14023==The signal is caused by a READ memory access.
==14023==Hint: address points to the zero page.
    #0 0x7f5624395ba4  (/lib/x86_64-linux-gnu/libc.so.6+0x18bba4)
    #1 0x7f5624f8b8fb  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x678fb)
    #2 0x7f56233f3a1b in dumpcffnames /home/fcambus/fontforge-20190801/fontforge/tottf.c:1795
    #3 0x7f56233ffb50 in dumptype2glyphs /home/fcambus/fontforge-20190801/fontforge/tottf.c:2634
    #4 0x7f562342907c in initTables /home/fcambus/fontforge-20190801/fontforge/tottf.c:5750
    #5 0x7f562342d475 in _WriteTTFFont /home/fcambus/fontforge-20190801/fontforge/tottf.c:6143
    #6 0x7f562342d611 in WriteTTFFont /home/fcambus/fontforge-20190801/fontforge/tottf.c:6171
    #7 0x7f5622fe00b4 in _DoSave /home/fcambus/fontforge-20190801/fontforge/savefont.c:845
    #8 0x7f5622fe2f7b in GenerateScript /home/fcambus/fontforge-20190801/fontforge/savefont.c:1269
    #9 0x7f5622ff99c4 in bGenerate /home/fcambus/fontforge-20190801/fontforge/scripting.c:2061
    #10 0x7f56230576bb in docall /home/fcambus/fontforge-20190801/fontforge/scripting.c:9632
    #11 0x7f562305855e in handlename /home/fcambus/fontforge-20190801/fontforge/scripting.c:9745
    #12 0x7f562305c8d0 in term /home/fcambus/fontforge-20190801/fontforge/scripting.c:9983
    #13 0x7f562305e1de in mul /home/fcambus/fontforge-20190801/fontforge/scripting.c:10128
    #14 0x7f562305eade in add /home/fcambus/fontforge-20190801/fontforge/scripting.c:10174
    #15 0x7f562305f9e7 in comp /home/fcambus/fontforge-20190801/fontforge/scripting.c:10249
    #16 0x7f562306044d in _and /home/fcambus/fontforge-20190801/fontforge/scripting.c:10293
    #17 0x7f5623060a79 in _or /home/fcambus/fontforge-20190801/fontforge/scripting.c:10325
    #18 0x7f5623061167 in assign /home/fcambus/fontforge-20190801/fontforge/scripting.c:10358
    #19 0x7f562306284f in expr /home/fcambus/fontforge-20190801/fontforge/scripting.c:10436
    #20 0x7f56230644de in ff_statement /home/fcambus/fontforge-20190801/fontforge/scripting.c:10649
    #21 0x7f5623065b92 in ProcessNativeScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10796
    #22 0x7f562306659f in _CheckIsScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10894
    #23 0x7f5623066881 in CheckIsScript /home/fcambus/fontforge-20190801/fontforge/scripting.c:10927
    #24 0x7f5624ba3be7 in fontforge_main /home/fcambus/fontforge-20190801/fontforgeexe/startui.c:1099
    #25 0x55e7ce3881ec in main /home/fcambus/fontforge-20190801/fontforgeexe/main.c:33
    #26 0x7f56242311e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #27 0x55e7ce38810d in _start (/home/fcambus/fontforge-20190801/fontforgeexe/.libs/fontforge+0x110d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x18bba4) 
==14023==ABORTING
```

### PR DESCRIPTION
**Pull request by skef**
Fix for #4084 Use-after-free (heap) in the SFD_GetFontMetaData() function
Fix for #4086 NULL pointer dereference in the SFDGetSpiros() function
Fix for #4088 NULL pointer dereference in the SFD_AssignLookups() function
Add empty sf->fontname string if it isn't set, fixing #4089 #4090 and many
  other potential issues (many downstream calls to strlen() on the value).

Closes #4084 
Closes #4086 
Closes #4088 
Closes #4089 
Closes #4090 

Meta-note: That I am continually annoyed at the number of open FontForge issues does not imply this is not a waste of time.

### CODE REVIEW

File: fontforge/sfd.c [hunk 1]
```diff
@@ -4032,13 +4032,16 @@ static void SFDGetSpiros(FILE *sfd,SplineSet *cur) {
     while ( fscanf(sfd,"%lg %lg %c", &cp.x, &cp.y, &cp.ty )==3 ) {
 	if ( cur!=NULL ) {
 	    if ( cur->spiro_cnt>=cur->spiro_max )
-		cur->spiros = realloc(cur->spiros,(cur->spiro_max+=10)*sizeof(spiro_cp));
+		cur->spiros = realloc(cur->spiros,
+		                      (cur->spiro_max+=10)*sizeof(spiro_cp));
```
Comment (ctrlcctrlv) [inline fontforge/sfd.c]:
```python
>>> L1="                cur->spiros = realloc(cur->spiros,(cur->spiro_max+=10)*sizeof(spiro_cp));"
>>> L2="""
		cur->spiros = realloc(cur->spiros,
		                      (cur->spiro_max+=10)*sizeof(spiro_cp));"""
>>> import re
>>> re.sub(r'\s+', '', L2) == re.sub(r'\s+', '', L1)
True
```

What is the purpose of the added line break?

Comment (skef) [reply fontforge/sfd.c]: Just increasing conformance with the mostly-followed 80 char/line rule while I was in the neighborhood.

**Comment by frank-trampe** [comment]
You guys played really hard-to-get on this one!

**Comment by skef** [comment]
@frank-trampe These sorta feel less like maintenance than gamification.

**Comment by frank-trampe** [comment]
It's all the rage these days.
