### PR TITLE
Fix GDrawDrawImageMagnififed and add bounds checking to GDrawDrawImage

### LINKED ISSUE #3919: Fontforge occasionally crashes on windows when zooming in with background image
#3469 # Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [X] Steps to reproduce the behavior 
- [X] \(optional) Possible solution/fix/workaround

Fontforge crashes when zooming in or out on an image
version: 2019-08-01, windows
reproduction steps:
-Open a new file
-Select any glyph
-Select back layer
-Upload a 1000by1000 pixel image in png format
-Try zooming in FontForge will occasionally crash

Note I tried this on 2 windows computers with entirely different specifications and build years.

workaround:
Before zooming in or out select the background and delete the image. After zooming use ctrl+z to bring it back.

### PR DESCRIPTION
**Pull request by jtanx**
Fixes the crash/oob memory access by fixing the casting of the pointer.

Also fixes the display of the image when at that zoom level.

### Type of change
- **Bug fix** Fixes #3919

### CODE REVIEW

File: gdraw/ggdkcdraw.c [hunk 1]
```diff
@@ -285,7 +285,7 @@ static cairo_surface_t *_GGDKDraw_GImage2Surface(GImage *image, GRect *src) {
     /*  premultiply each channel by alpha. We can reuse it for non-transparent*/
     /*  rgb images */
     if (base->image_type == it_true && type == CAIRO_FORMAT_RGB24) {
-        idata = ((uint32 *)(base->data)) + src->y * base->bytes_per_line + src->x;
+        idata = ((uint32 *)(base->data + src->y * base->bytes_per_line)) + src->x;
```
Comment (jtanx) [inline gdraw/ggdkcdraw.c]: This fixes the oob memory access

File: gdraw/gdraw.c [hunk 2]
```diff
@@ -477,14 +476,40 @@ void GDrawScroll(GWindow w, GRect *rect, int32 hor, int32 vert) {
 
 /* draws the subset of the image specified by src starting at loc (x,y) */
 void GDrawDrawImage(GWindow w, GImage *img, GRect *src, int32 x, int32 y) {
-    GRect r;
-    if ( src==NULL ) {
-	struct _GImage *base = img->list_len==0?img->u.image:img->u.images[0];
-	r.x = r.y = 0;
-	r.width = base->width; r.height = base->height;
-	src = &r;
+    int width = GImageGetWidth(img);
```
Comment (jtanx) [inline gdraw/gdraw.c]: All the changes here and in charview.c are to fix what gets displayed when at that zoom level.

File: gdraw/ggdkcdraw.c (hunk 1 above)
Comment (psychon) [reply gdraw/ggdkcdraw.c]: Assuming `base->data` is a byte-sized pointer (e.g. `char*`): This one line of the change looks good to me. I did not look at anything else in here.
