### PR TITLE
Fix painting behaviour of the ruler linger window and layer change dialog

### LINKED ISSUE #5119: GGDKDraw assertion failure when using ruler
@jtanx when I use the ruler tool in the current master (Arch Linux, debug build) I get an assertion failure just when the tool snaps to the second point: `fontforge: /home/skef/src/ff3/gdraw/ggdkcdraw.c:52: _GGDKDraw_CheckAutoPaint: Assertion 'false && "No window should be drawing outside of expose calls"' failed.`

I've only tried with a couple files (always cubic so far) but it seems to happen every time.

### PR DESCRIPTION
**Pull request by jtanx**
Fixes #5119

### Type of change

- **Bug fix**

### CODE REVIEW

File: fontforgeexe/cvruler.c [hunk 1]
```diff
@@ -1003,6 +1003,5 @@ return;
 	    }
 	    prev_rect = rect;
 	}
-	RulerLingerMove(cv);	/* in case things are moving or scaling */
```
Comment (jtanx) [inline fontforgeexe/cvruler.c:1006]: Instead of calling this from the expose event, I call it in response to the charview doing a scroll or zoom.

**Review by skef — APPROVED** [review]
lgtm

**Comment by skef** [comment]
This second commit looks OK too, given that the timer is set just before.
