### PR TITLE
Correct bad comparison when building MetricsView

### LINKED ISSUE #4627: Ā appears as "\uni0100" in MetricsView despite the fact "ā" appears as "ā"
If you select Ā in the FontView and open a MetricsView, it appears as "\uni0100" in MetricsView despite the fact "ā" appears as "ā".

I already know what's wrong and have a PR, this is a tracking issue.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Makes it so when you select Ā in the FontView and open a MetricsView it
appears correctly as Ā, not as `\uni0100`.

Close #4627

### Type of change

- **Bug fix**

### CODE REVIEW

File: fontforgeexe/metricsview.c [hunk 1]
```diff
@@ -5291,7 +5291,7 @@ MetricsView *MetricsViewCreate(FontView *fv,SplineChar *sc,BDFFont *bdf) {
 
     for ( cnt=0; cnt<mv->clen; ++cnt ) {
         int cp = mv->chars[cnt]->unicodeenc;
-        if ( cp != -1 && strchr("#[]/\\", cp) == NULL)
+        if ( cp != -1 && u_strchr(L"#[]/\\", cp) == NULL )
```
Comment (jtanx) [inline fontforgeexe/metricsview.c:5294]: Still not quite correct, a wchar_t on windows is 2 bytes/UCS-2, not 4.

File: fontforgeexe/metricsview.c [hunk 2]
```diff
@@ -5291,7 +5291,7 @@ MetricsView *MetricsViewCreate(FontView *fv,SplineChar *sc,BDFFont *bdf) {
 
     for ( cnt=0; cnt<mv->clen; ++cnt ) {
         int cp = mv->chars[cnt]->unicodeenc;
-        if ( cp != -1 && strchr("#[]/\\", cp) == NULL)
+        if ( cp != -1 && u_strchr((unichar_t[]){'#', '[', ']', '/', '\\'}, cp) == NULL )
```
Comment (jtanx) [inline fontforgeexe/metricsview.c:5294]: This is missing a null terminator, it might also be a bight clearer if you define it as `static const unichar_t*` out of line

**Review by jtanx — APPROVED** [review]
