### PR TITLE
Always normalise the file path out of GFileChooser

### LINKED ISSUE #2834: Entering path in import dialogue with backslashes results in segfault
* Go to File->Import
* Enter a file path, e.g. C:\my\folder
* Hit ok
* Crash

~~~~~
#0  0x6e8892aa in FVImportBDF (fv=0x3d04138, filename=0x43c2dd8 "C:\\my\\path", ispk=0, toback=0) at fvimportbdf.c:22
86
#1  0x6365f3f7 in GFD_ImportOk (g=0x43c1f90, e=0x60ec60) at cvimportdlg.c:437
#2  0x6ef9517b in _GWidget_TopLevel_Key (top=0x43b9570, ew=0x43b9570, event=0x60
ed88) at gcontainer.c:552
#3  0x6ef9574d in _GWidget_TopLevel_eh (gw=0x43b9570, event=0x60ed88) at gcontai
ner.c:680
...
~~~~~

### PR DESCRIPTION
**Pull request by jtanx**
### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)

### Description
This ensures that backslashes are always converted to slashes on
Windows, which is necessary as other code assumes slashes for the
path separator.

This also removes the burden of having to normalise the output by
the caller instead of doing it in the GFC.

Fixes #2834

cc @frank-trampe

### CODE REVIEW

File: fontforgeexe/openfontdlg.c [hunk 1]
```diff
@@ -457,7 +457,7 @@ static int GFD_Ok(GGadget *g, GEvent *e) {
 return(true);
 	    }
 	    d->done = true;
-	    d->ret = u_GFileNormalizePath(GGadgetGetTitle(d->gfc));
```
Comment (frank-trampe) [inline fontforgeexe/openfontdlg.c]: Was this leaking?

Comment (frank-trampe) [inline fontforgeexe/openfontdlg.c]: Wait, never mind.

Comment (jtanx) [inline fontforgeexe/openfontdlg.c]: No. GGadgetGetTitle returns a copy. u_GFileNormalizePath modifies in-place.

**Comment by jtanx** [comment]
It looks like gnu.org is down.

**Comment by frank-trampe** [comment]
I knew all of that Microsoft-bashing would catch up to Richard Stallman someday.

**Comment by frank-trampe** [comment]
Actually, it turns out that it's just part of a revenue model transition. See [here](http://diafygi.github.io/gnu-pricing/website/).
