### PR TITLE
FindMonotonicIntersection fix and splineoverlap cleanup

### LINKED ISSUE #529: Remove overlap stuck in infinite loop on 32-bit Linux
This seems very similar to #257, but the fix for #257 doesn't seem to have fixed it.  Load https://github.com/fontforge/debugfonts/blob/master/rmo-loop2.sfd , select the glyph it contains, remove overlaps, infinite loop.  Tested with the latest master head revision; fails on 32-bit Linux; doesn't fail on 64-bit Linux.

### PR DESCRIPTION
**Pull request by jtanx**
I turned up the warnings on splineoverlap.c and fixed most of them. I've `#if 0`'ed a bunch of code, but I'd prefer to just delete it.

Fix for FindMonotonicIntersection is to properly calculate the diff instead of doing that `bkp_x`/`bkp_y` logic.

### Type of change

- **Bug fix**
- **Non-breaking change**

Fixes #529. Relates to #3991.

### CODE REVIEW

File: fontforge/splineoverlap.c [hunk 1]
```diff
@@ -1808,12 +1792,8 @@ return;		/* Not interesting. Only intersection is at an endpoint */
 			oncebefore = true;
 		    }
 
-		    /* This is a volatile code! */
-		    /* "diff" may become so small in comparison with "y", */
-		    /* that "y+=diff" might actually not change the value of "y". */
-		    // So we double diff until it is significant.
-		    bkp_y=y+diff;
-		    while (bkp_y==y) { diff *= 2; bkp_y = y+diff; }
+		    diff = CalculateMinimumDiff(y, diff);
```
Comment (jtanx) [inline fontforge/splineoverlap.c]: So this is pretty much the fix for the issue discussed in #3991 / #529

**Comment by jtanx** [comment]
Good thing I had that assert, I misread the docs on nextafter...

**Comment by skef** [comment]
Consider my approval amended to include that fix.
