### PR TITLE
fvimportbdf.c: Fix FVImportBDF when path has no slash in it

### LINKED ISSUE #3838: python: importBitmaps segmentation fault
* Arch Linux (using my own fontforge-git)

* fontforge 20190413
* build date: 07:51 UTC 30-Jul-2019

Due to [recent changes in pango 1.44](https://gitlab.gnome.org/GNOME/pango/issues/386), it no longer loads PCF or BDF (among others) font formats.  As a result I'm attempting to write a script that can absorb PCF and BDF files and generate an "OpenType Bitmap" font.  I have what appears to work using fontforge's own scripting language but when porting it to the python API I've run into a case of segmentation faults on some PCF files, notably terminus.

```py
#!/usr/bin/env python3

import sys
from fontforge import font


def main(argc, argv):
    if argc == 1:
        print('usage: opentype-bitmap font-size1.pcf [font-size2.pcf ...]',
              file=sys.stderr)
        sys.exit(1)

    n = font()

    for arg in argv[1:]:
        print(f'opentype-bitmap: {arg}: loading bitmap strikes',
              file=sys.stderr)
        n.importBitmaps(arg)

    n.generate(n.fullname + '.otb', 'otb')
    print(n.fullname + '.otb')


if __name__ == '__main__':
    main(len(sys.argv), sys.argv)
```

While this appears to have no issue with many PCF and BDF files, it crashes when attempting to open any one of terminus's PCF files:

```
% file ter-x14n.pcf
ter-x14n.pcf: X11 Portable Compiled Font data, bit: MSB, byte: MSB first

% ./opentype-bitmap.py ter-x14n.pcf
opentype-bitmap: ter-x14n.pcf: loading bitmap strikes
zsh: segmentation fault (core dumped)  ./opentype-bitmap.py ter-x14n.pcf
```

Here is a backtrace:

```
#0  0x00007f53c471826c in FVImportBDF (fv=fv@entry=0x556e62b2e120, filename=filename@entry=0x556e62b2e2a0 "ter-x12n.pcf", ispk=ispk@entry=2, toback=0) at fvimportbdf.c:2306
#1  0x00007f53c47bf2ff in PyFFFont_importBitmaps (self=0x7f53c4b8bef0, args=<optimized out>) at python.c:14140
#2  0x00007f53c5bc85df in _PyMethodDef_RawFastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#3  0x00007f53c5bfa11f in _PyMethodDescr_FastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#4  0x00007f53c5bfa2b4 in  () at /usr/lib/libpython3.7m.so.1.0
#5  0x00007f53c5c2ff70 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.7m.so.1.0
#6  0x00007f53c5be9633 in _PyFunction_FastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#7  0x00007f53c5bfa1d0 in  () at /usr/lib/libpython3.7m.so.1.0
#8  0x00007f53c5c2fed7 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.7m.so.1.0
#9  0x00007f53c5be8768 in _PyEval_EvalCodeWithName () at /usr/lib/libpython3.7m.so.1.0
#10 0x00007f53c5be952a in PyEval_EvalCodeEx () at /usr/lib/libpython3.7m.so.1.0
#11 0x00007f53c5c7909c in PyEval_EvalCode () at /usr/lib/libpython3.7m.so.1.0
#12 0x00007f53c5cbd815 in  () at /usr/lib/libpython3.7m.so.1.0
#13 0x00007f53c5cbdd9b in PyRun_FileExFlags () at /usr/lib/libpython3.7m.so.1.0
#14 0x00007f53c5cc48a7 in PyRun_SimpleFileExFlags () at /usr/lib/libpython3.7m.so.1.0
#15 0x00007f53c5cc6aa8 in  () at /usr/lib/libpython3.7m.so.1.0
#16 0x00007f53c5cc6c5c in _Py_UnixMain () at /usr/lib/libpython3.7m.so.1.0
#17 0x00007f53c5e30f83 in __libc_start_main (main=
    0x556e61279020 <main>, argc=11, argv=0x7ffdb0df5ce8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdb0df5cd8)
    at ../csu/libc-start.c:308
#18 0x0000556e6127905e in _start ()
```

Curiously during building of fontforge I get this error from gcc (there are a few others like it):

```
In function ‘PcfParse’,
    inlined from ‘SFImportBDF’ at fvimportbdf.c:2165:8:
fvimportbdf.c:1808:17: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 1808 |     b->glyphs = calloc(mcnt,sizeof(BDFChar *));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/gutils.h:306,
                 from /usr/include/glib-2.0/glib/gthread.h:34,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from ../inc/ffglib.h:29,
                 from baseviews.h:31,
                 from fvimportbdf.h:4,
                 from fvimportbdf.c:30:
fvimportbdf.c: In function ‘SFImportBDF’:
/usr/include/stdlib.h:542:14: note: in a call to allocation function ‘calloc’ declared here
  542 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
```

### PR DESCRIPTION
**Pull request by jtanx**
Fixes #3838

### Type of change

- **Bug fix**\

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Looks good to me. Sorry about thinking it was a regression @jtanx, I didn't test myself, just believed user's erroneous report

**Comment by Earnestly** [comment]
Can confirm it fixes https://github.com/fontforge/fontforge/issues/3838

File: fontforge/fvimportbdf.c [hunk 1]
```diff
@@ -2303,22 +2303,26 @@ int FVImportBDF(FontViewBase *fv, char *filename, int ispk, int toback) {
     int oldenccnt = fv->map->enccount;
 
     eod = strrchr(filename,'/');
```
Comment (skef) [inline fontforge/fvimportbdf.c]: Could we add `pathname`, copy filename up to `eod-1` into it in the first case and `copy(".");` in the second, and free at the bottom? It seems better to leave the caller's string unmolested "as long as we're here".
